Add new APIs for generating SGIs
seL4/seL4 pull request #1222
Opened 2024-03-14 13:45 UTC by lsf37

This is work by @kent-mcleod, with an additional commit on top from myself with verification tweaks for this new API.

For design rationale and background on the API in this PR see [RFC-17](https://sel4.atlassian.net/browse/RFC-17).

2024-03-14 13:46 UTC, lsf37 commented
@kent-mcleod could you please add the sign-off to your commit?

2024-03-14 15:59 UTC, Indanz requested changes
I can't think of any useful use case where the user would want to send IPIs to multiple cores **and** knows which those are beforehand, with the only exception being all other cores.

I don't think supporting sending multiple IPIs at once is necessary or worth the added complexity. But if it is added, it should fully expose the hardware in a useful way. The current implementation is limited to systems with one cluster of at most 16 cores.

With that in mind, I propose the API is changed to either allowing only one target core, or:

- Add a mask parameter to the call which is ANDed with the configured mask.
- Configure `Aff1, `Aff2` and `Aff3` at creation time (but good luck to user space figuring out what they need to fill in though).
- Give an option to send to all other cores (`IRM = 1`).
- Expose `RS`.

Then at least the API is future proof for a while, till ARM comes with a new interface for sending multiple IPIs. Mind that with the above changes it probably doesn't make any sense to share `ipi_send_target()`.

2024-03-14 15:59 UTC, Indanz commented on libsel4/arch_include/arm/interfaces/sel4arch.xml
> +            <param dir="in" name="index" type="seL4_Word" description="CPTR to the destination slot. Resolved from the root of the destination CSpace."/>
```suggestion
            <param dir="in" name="root" type="seL4_CNode" description="CPtr to the CNode that forms the root of the destination CSpace. Must be at a depth equivalent to the wordsize."/>
            <param dir="in" name="index" type="seL4_Word" description="CPtr to the destination slot. Resolved from the root of the destination CSpace."/>
```

2024-03-14 16:18 UTC, lsf37 commented on src/arch/arm/object/interrupt.c
> +    } else if (invLabel == ARMIRQIssueSGISignal) {
I like it slightly better here. The case is very close in content (which checks it does) to ARMIRQIssueIRQHandlerTrigger. Moving it further away will mean they will diverge more easily.

2024-03-14 16:19 UTC, lsf37 commented
It's a bit early to review the PR (should have left it on draft). We should sort out the API in the RFC discussion first.

2024-03-14 16:21 UTC, lsf37 commented
@kent-mcleod there are a few Arm platforms that don't use `gic_v2.h` or `gic_v3.h`, which means they are currently not defining the right interface functions. If the RFC is accepted, these will need to be added.

2024-03-14 16:25 UTC, Indanz commented on src/arch/arm/object/interrupt.c
> +    } else if (invLabel == ARMIRQIssueSGISignal) {
Fair enough.

2024-03-14 19:42 UTC, lsf37 commented
> > It's a bit early to review the PR (should have left it on draft). We should sort out the API in the RFC discussion first.
> 
> The RFC is higher level and doesn't propose a specific API though, it actually says:
> 
> `For the first implementation we'll only support unicast signalling, but broadcast and multicast functionality can be added later via extensions to the IRQControl invocation that creates the IPI cap.`

Fair enough, the code actually has slightly more than the RFC proposes. We  should update the RFC then, the API decisions need to be there.

2024-03-14 23:09 UTC, kent-mcleod commented
>     * Add a mask parameter to the call which is ANDed with the configured mask.

This was in the earliest iteration of the design, but was taken out in favor of having 0 arguments to the call so that the capability could be interchanged with a regular Notification capability with send rights.

> 
>     * Configure `Aff1`, `Aff2` and `Aff3` at creation time (but good luck to user space figuring out what they need to fill in though).
> 
>     * Give an option to send to all other cores (`IRM = 1`).
> 

In principle, the capabilities of the hardware should be exposed, so I agree that higher order affinities and IRM could be configured at cap creation time, and equivalent for GICv2 (which doesn't support affinity routing but does support broadcast).  There's also potentially a future need to select a different interrupt group or security state, which is encoded by which SGIR is used. There's enough spare bits in the capability to encode all of these options, but we don't have an easy setup to test the different combinations. 



>     * Expose `RS`.
> 

I'm not sure what `RS` refers to.

2024-03-14 23:57 UTC, axel-h commented on include/arch/arm/arch/32/mode/object/structures.bf
> +#if CONFIG_MAX_NUM_NODES == 1
Why don't we check `CONFIG_SMP_ENABLED` here and in the other places? Or add a dedicated feature define for this, so using  `CONFIG_MAX_NUM_NODES` directly is avoided. On RISC-V I have been running into some use cases now where having certain multi core feature available even with just one seL4 core comes handy and the checks for `CONFIG_MAX_NUM_NODES` are a pain then.

2024-03-15 09:27 UTC, Indanz commented
> Fair enough, the code actually has slightly more than the RFC proposes. We should update the RFC then, the API decisions need to be there.

I'm happy to move the discussion to the RFC.

> I'm not sure what `RS` refers to.

It enables [range selector](https://developer.arm.com/documentation/ddi0601/2020-12/AArch64-Registers/ICC-SGI1R-EL1--Interrupt-Controller-Software-Generated-Interrupt-Group-1-Register?lang=en#fieldset_0-47_44), in case max 256 cores at `Aff0` are supported.

The only future proof way is to store the full 64 bits, then the API doesn't need to change if ARM uses one of the reserved bits in the future. 32-bit ARM should be stable enough by now.

2024-03-22 04:08 UTC, kent-mcleod commented
> It enables [range selector](https://developer.arm.com/documentation/ddi0601/2020-12/AArch64-Registers/ICC-SGI1R-EL1--Interrupt-Controller-Software-Generated-Interrupt-Group-1-Register?lang=en#fieldset_0-47_44), in case max 256 cores at `Aff0` are supported.

Ah, I've only been working off of the gicv3.0 manual because we don't have any plans for platforms with the higher revisions at this stage.

2024-06-17 23:56 UTC, kent-mcleod commented
@Indanz, I'm about to make the changes for supporting higher level affinity bits. Here is what I'm considering for the cap definition. (this is the aarch32 definition. The same can be used for aarch64, but with more padding for the extra 64bits).
```
block sgi_signal_cap {
    field padding           18
    -- SecureState and GroupSel together select the target
    -- security and group classification. In GICv3 this chooses
    -- between SGI0R, SGI1R and ASGI1R. If groupSel is set to
    -- indicate group 0, then the value of SecureState is ignored.
    field capSGISecureState 1
    field capSGIGroupSel    1
    -- Aff0 is 4 bits because only 16 addresses are supported
    -- by the interrupt controller specification.
    -- The RangeSel field can be used to select which 
    field capSGIAff0        4
    field capSGIRangeSel    4
    -- IRQ is the irq ID to send (0-15)
    field capSGIIRQ         4

    field capSGIAff1        8
    field capSGIAff2        8
    field capSGIAff3        8
    field capType           8
}
```

Because gicv2 and early versions of gicv3 don't support all the functionality encoded here it seems easiest to detect features by the GIC hardware version during kernel init and then return errors to ARMIRQIssueSGISignal if unsupported configurations are requested.
On GICv2, only capSGIIRQ (0-15), capSGIAff0 (0-7) and capSGIGroupSel (0-1) can be set.
On GICv3.0 all values except capSGIRangeSel can be set I believe.
There aren't currently any platforms that seL4 supports with a newer version of GICv3 that supports the RangeSelect field afaik.

2024-06-18 11:46 UTC, Indanz commented
> @Indanz, I'm about to make the changes for supporting higher level affinity bits. Here is what I'm considering for the cap definition. (this is the aarch32 definition. The same can be used for aarch64, but with more padding for the extra 64bits).
> 
> ```
> block sgi_signal_cap {
>     field padding           18
>     -- SecureState and GroupSel together select the target
>     -- security and group classification. In GICv3 this chooses
>     -- between SGI0R, SGI1R and ASGI1R. If groupSel is set to
>     -- indicate group 0, then the value of SecureState is ignored.
>     field capSGISecureState 1
>     field capSGIGroupSel    1
>     -- Aff0 is 4 bits because only 16 addresses are supported
>     -- by the interrupt controller specification.
>     -- The RangeSel field can be used to select which 
>     field capSGIAff0        4
>     field capSGIRangeSel    4
>     -- IRQ is the irq ID to send (0-15)
>     field capSGIIRQ         4
> 
>     field capSGIAff1        8
>     field capSGIAff2        8
>     field capSGIAff3        8
>     field capType           8
> }
> ```

I think you're making it unnecessarily complicated, I don't think it's necessary to store so many fields in the cap.

I don't think we need to support sending secure interrupts. On GICv3 we also only send group 1 interrupts. If you do want to make it possible to control the value of `NSATT`, it can always be emulated by different target IDs or IRQs, e.g. high bit determines the value of `NSATT`.

I would reduce the fields to just the IRQ and the target core ID, where the latter is a concatenation of `Aff0`, `RS`, `Aff1`, `Aff2` and `Aff3` for GICv3 (~=MPIDR) and for GICv2 just `target` (and possible `NSATT`, if it's wanted and not combined with the IRQ instead). This should of course be documented. It may look more complex for the user, but in reality it will be a very simple interface to use.

When the hardware is weird and has a noncontinuous target ID range because of core clusters, it's already hard to figure out which core has what ID. Doing some translation from a logical range to the actual MPID might be nice to have, but also very hard to figure out for the kernel. On SMP seL4 has `mpidr_map` for exactly that purpose, but that stores the Elfloader provided logical core ID.

To help with this we could provide a syscall that returns the current core's logical core ID and its target ID. How else is user space supposed to know on what core it runs?

> Because gicv2 and early versions of gicv3 don't support all the functionality encoded here it seems easiest to detect features by the GIC hardware version during kernel init and then return errors to ARMIRQIssueSGISignal if unsupported configurations are requested. On GICv2, only capSGIIRQ (0-15), capSGIAff0 (0-7) and capSGIGroupSel (0-1) can be set. On GICv3.0 all values except capSGIRangeSel can be set I believe. There aren't currently any platforms that seL4 supports with a newer version of GICv3 that supports the RangeSelect field afaik.

For GICv3 it's save to write bogus values, there will just be no interrupt generated, or in case of bad `RS`, possibly ignored and treated as zero. Same for GICv2. So it's not necessary to do such checking, doing it would be purely for user friendliness.

2024-06-18 17:07 UTC, Indanz commented
> I would reduce the fields to just the IRQ and the target core ID, where the latter is a concatenation of `Aff0`, `RS`, `Aff1`, `Aff2` and `Aff3` for GICv3 (~=MPIDR)

`Aff0` is actually the 4-bit target combined with the 4-bit `RS` value, so the target core ID would be just a concatenation of `Aff0`, `Aff1`, `Aff2` and `Aff3`.

2024-06-19 22:21 UTC, kent-mcleod commented
Ok, I'll just use a 32bit capSGITarget and 4 bit capSGIIRQ fields for now. 

In the call there was a request to expose GICv3 SGI targeting functionality through the control cap which should include targeting the alternate security state and group 0. We haven't needed this capability yet ourselves so I have no problem adding it in later.

2024-06-19 22:43 UTC, lsf37 commented
> Ok, I'll just use a 32bit capSGITarget and 4 bit capSGIIRQ fields for now.

👍 

> In the call there was a request to expose GICv3 SGI targeting functionality through the control cap which should include targeting the alternate security state and group 0. We haven't needed this capability yet ourselves so I have no problem adding it in later.

Happy to do that incrementally based on need. I actually only remember that we decided to add the higher affinity bits, which I thought were the `Aff0`, `Aff1`, `Aff2` and `Aff3` that Indan mentioned.

2024-06-20 01:31 UTC, kent-mcleod commented
`plat_SGITargetValid` and `plat_sendSGI` are added to allow platforms that don't support SGI to still build and run without adding a new compile config option.  Alternatively, we put the invocation behind a CONFIG_* flag.

2025-02-18 22:30 UTC, lsf37 commented
Have rebased the branched and merged in Kent's edits for the TSC feedback. I think this is now ready to merge. @Indanz could you have another look, please?

2025-02-18 22:30 UTC, lsf37 commented
(still have to update the verification to take Kent's changes into account )

2025-02-18 22:39 UTC, lsf37 commented on include/arch/arm/arch/32/mode/object/structures.bf
> +#if CONFIG_MAX_NUM_NODES == 1
Yes, makes sense. Will fix those up.

2025-02-18 23:02 UTC, lsf37 commented
(sorry for the force pushes, they were for the review feedback that I thought I had already done -- all done now)

2025-02-20 14:07 UTC, Indanz approved these changes
Overall looks good to me. Some small nitpicks here and there, of which most might have become obsolete because of later commits, so please ignore those.

Main things are:

- Why the exception for SMP? I would Just enable it always and also get rid of the debug IPI send syscall.
- It's a bit fuzzy whether SGI caps are common or arch specific.

2025-02-20 14:15 UTC, Indanz commented
(Github glitch posted my review twice.)

2025-02-20 22:24 UTC, lsf37 commented
> * Why the exception for SMP? I would Just enable it always and also get rid of the debug IPI send syscall.
> * It's a bit fuzzy whether SGI caps are common or arch specific.

SGI caps are arch specific. The mechanism is slightly different on each architecture and seL4 will in general not try to provide an abstraction for such things, just provide access to the hardware feature within the authorisation framework.

They are only implemented for Arm at the moment and will need a bit more thinking and additional implementation + verification for RISCV and x64. That's also the reason why it can't generically replace the debug IPI call yet. (Also it's not clear to me that we have enough guards in place to not interfere with the kernel's own use of IPI/SGI for the lock.)

Adding the mechanism for RISCV and x64 and removing debug IPI can be done, and maybe should be done, but it should be a separate step.

2025-02-21 12:08 UTC, kent-mcleod commented
So on GICv2 there's a separate interrupt state for each {sgi x source CPU x target CPU} combination (for a maximum of 8 CPUs).  Something that I've only just realized is that there should be a distinct IRQ CNode slot for each of these, but currently the kernel only provides a single slot for each SGI. So for a single core that can receive SGIs via a gicv2, there's currently 16 CNode slots allocated, but it should actually be 16 x n where n is the number of GICv2 CPU interfaces that exist on the platform. 
Sooo we should probably extend the IRQ CNode to track these and allow the IRQ control cap to generate specific handlers.

2025-02-21 12:51 UTC, Indanz commented
> So on GICv2 there's a separate interrupt state for each {sgi x source CPU x target CPU} combination (for a maximum of 8 CPUs). Something that I've only just realized is that there should be a distinct IRQ CNode slot for each of these, but currently the kernel only provides a single slot for each SGI. So for a single core that can receive SGIs via a gicv2, there's currently 16 CNode slots allocated, but it should actually be 16 x n where n is the number of GICv2 CPU interfaces that exist on the platform.

Now that you mention it, all the changes are for sending SGIs, but I see no changes to accommodate receiving SGIs at all.

> Sooo we should probably extend the IRQ CNode to track these and allow the IRQ control cap to generate specific handlers.

On the sending side, none of this changes anything, does it? I don't see an advantage to restrict the sending core for an SGI handle, and sending SGIs is a stateless operation.

2025-03-06 05:29 UTC, lsf37 commented on src/arch/arm/object/interrupt.c
> +            return EXCEPTION_SYSCALL_ERROR;
I think it's fine like this, it has fewer assumptions on what the platform supports, and it's not likely that the target range will be a mystery to the user when they are focussing on a specific platform.

2025-03-06 05:31 UTC, lsf37 commented on src/object/cnode.c
> +    }
I want the arch checks before the switch, so here is good. They don't intersect, so techincally it doesn't really matter, but it's easier in the proof structure to take care of them first.

2025-03-06 05:35 UTC, lsf37 commented on src/object/cnode.c
> +    }
The default return in `Arch_isMDBParentOf` is `true` , which might sound a bit weird. A better name for the function would be `Arch_canMDBParentOf`. What I really want to know after this point is that I don't have to take care of arch caps any more.

2025-03-06 05:45 UTC, lsf37 commented on src/arch/arm/machine/gic_v3.c
> +}
I'm currently adding the check (same as for GICv2), but it looks like the max number of targets there is currently set to 16 (and otherwise unused after the update). So we still have a TODO item on either configuring that value per platform or looking up at boot time what the hardware supports.

- [ ] set `GIC_SGI_NUM_TARGETS` correctly

2025-03-06 05:45 UTC, lsf37 commented on src/arch/arm/machine/gic_v2.c
> +    return target < GIC_SGI_TARGET_MASK_BITS;
Agreed. Changing it to `GIC_SGI_NUM_TARGETS`, since `GIC_SGI_MAX_TARGET` would imply that we should use `<=`.

2025-03-06 05:52 UTC, lsf37 commented on src/object/objecttype.c
> +            Arch_isIRQControlDescendant(cap_b)) {
Probably better to leave it like this. Either way we have the new situation of comparing an arch cap to a generic cap. For `Arch_sameRegionAs` and `Arch_sameObjectAs`, the proofs currently focus down on just arch caps (i.e. the lemmas already have an ArchCap pattern), so it's easer to treat the case up here.

2025-03-06 11:18 UTC, Indanz commented on src/object/cnode.c
> +    }
A comment would be good.

2025-03-06 11:41 UTC, Indanz approved these changes

2025-03-06 11:47 UTC, Indanz commented
> Edit: Looks like receiving will just work, except for the above issue where the slot is not indexed properly. You would need a similar fix as is done for PPIs in `IRQT_TO_IDX` and then everything should work fine?

The sending side seems ready, for receiving SGIs the above may need to be fixed.

Would be good to have a sel4test that checks the functionality end-to-end before merging.

2025-03-06 22:13 UTC, lsf37 commented
> > Edit: Looks like receiving will just work, except for the above issue where the slot is not indexed properly. You would need a similar fix as is done for PPIs in `IRQT_TO_IDX` and then everything should work fine?
> 
> The sending side seems ready, for receiving SGIs the above may need to be fixed.

👍 
 
> Would be good to have a sel4test that checks the functionality end-to-end before merging.

Agreed, that would be good. Invoking the sending side is easy, but testing the receive is actually a bit annoying, because sel4test doesn't have any multikernel configs, and I'm not quite sure how that would even work. Any thoughts on how we would do that?

It might actually be easier to test this in the CAmkES multikernel example setup that @kent-mcleod is preparing.

2025-03-06 22:15 UTC, kent-mcleod commented
There should be no issues for receiving, just that in order to set the split EOI mode setting for GICv2, the source processor ID would need to be encoded in the IRQ handler cap. But with how the GICv2 works presently, the kernel combines multiple SGIs with the same IRQ number from different cores.
SGI's can't be disabled at the distributor, so the masking operation that we do doesn't actually have any effect AFAIK.  The split EOI mode would address this.

2025-03-06 22:18 UTC, Indanz commented
> > Would be good to have a sel4test that checks the functionality end-to-end before merging.
> 
> Agreed, that would be good. Invoking the sending side is easy, but testing the receive is actually a bit annoying, because sel4test doesn't have any multikernel configs, and I'm not quite sure how that would even work. Any thoughts on how we would do that?

I think we should add multikernel support to sel4test.

2025-03-06 22:19 UTC, kent-mcleod commented
> It might actually be easier to test this in the CAmkES multikernel example setup that @kent-mcleod is preparing.

I've been preparing a newer set of changes over the last couple weeks. There's currently only 1 working configuration which uses a gicv2 that's more up to date (it has the commits from this branch as of around monday):
```
repo init -u https://github.com/kent-mcleod/camkes-vm-examples-manifest -m master.xml -b kent/multicore3
repo sync -j12
mkdir build && cd build
../init-build.sh -DPLATFORM=zcu102 -DCAMKES_VM_APP=vm_multikernel_minimal -DRELEASE=OFF
ninja
```
Then from u-boot on a zcu102: bootelf 0x10000000 once the elf file produced by the build has been loaded into memory.

2025-03-06 22:24 UTC, kent-mcleod commented
> I think we should add multikernel support to sel4test.

Yea, and sel4bench. 

In both cases, it would require a different build target configuration that defines the static address map for multikernels.
- the elfloader and the CMake build can construct multiple kernels and root servers and boot them,
- We'd need to add a new proxy rootserver for each that would respond to requests from the primary rootserver.
- Maybe we should pass mpidr through the seL4_BootInfo...

2025-03-09 22:32 UTC, lsf37 commented on src/arch/arm/machine/gic_v3.c
> +}
Ok, happy to leave it as a `<` check on the number of SGIs supported by the GIC spec.

2025-03-09 23:33 UTC, lsf37 commented on libsel4/arch_include/arm/interfaces/object-api-arch.xml
> +            <param dir="in" name="target" type="seL4_Word" description="The node ID that will be targeted."/>
I've updated and expanded the description, and it became clear to me that I don't actually know what the behaviour is when we raise an SGI with an unsupported target. We'll end up setting a target bit or an affinity bit that is not supported. What does the hardware do in that case? Do we know that it does nothing? Or are we ending up signalling core 0, because the unsupported bits are ignored and we end up with an all-zero bit mask?

Either would be fine, but we should document what it is (currently I'm saying "nothing happens")

2025-03-12 22:51 UTC, lsf37 commented
(fixed a missing argument error number and added a commit to fix the same for `ARMIRQIssueIRQHandlerTriggerCore`)

2025-03-12 22:58 UTC, lsf37 commented on libsel4/include/api/syscall.xml
>          </config>
@kent-mcleod was this intentional? It doesn't look to me like `DebugSendIPI` should be available in multikernel configs.

2025-03-13 01:19 UTC, kent-mcleod commented on libsel4/arch_include/arm/interfaces/object-api-arch.xml
> +            <param dir="in" name="target" type="seL4_Word" description="The node ID that will be targeted."/>
The lowest level target list is a bit mask, so if no bits are set then no SGI would be generated.
In the case where there's a valid target address given but no target exists with that address then it's ignored by the distributor. (It could generate a system error, but this is unlikely in our experience):
"
If a bit is 1 and the bit does not correspond to a valid target PE, the bit must be ignored by the Distributor. It is IMPLEMENTATION DEFINED whether, in such cases, a Distributor can signal a system error.
"

2025-03-13 01:22 UTC, kent-mcleod commented on libsel4/include/api/syscall.xml
>          </config>
It was intentional but it's not a required change. Mainly because the CONFIG_ENABLE_SMP_SUPPORT was previously required because the implementation was behind the CONFIG_ENABLE_SMP_SUPPORT flag.  Because the implementation moved out of the CONFIG_ENABLE_SMP_SUPPORT flag, there was no reason for preventing it at the config level.

2025-03-13 07:55 UTC, lsf37 commented on libsel4/include/api/syscall.xml
>          </config>
Ok, makes sense. I guess it does not hurt and it's debug functionality anyway. Happy to leave it as is.

2025-03-13 07:57 UTC, lsf37 commented on libsel4/arch_include/arm/interfaces/object-api-arch.xml
> +            <param dir="in" name="target" type="seL4_Word" description="The node ID that will be targeted."/>
Ok, good. What happens when the distributor signals a system error? Are we receiving that as a hardware exception on the current core when we leave the kernel? Or might it interrupt the kernel?

2025-03-13 08:16 UTC, Indanz commented
On 2025-03-13 07:57, Gerwin Klein wrote:
> Ok, good. What happens when the distributor signals a system error?
> Are we receiving that as a hardware exception on the current core when
> we leave the kernel? Or might it interrupt the kernel?

Probably an SError, which by default halts the system because seL4 takes 
it too seriously. So practically doesn't matter whether it happens 
immediately or later.

Just like writing to some read-only device registers.

2025-07-06 22:50 UTC, lsf37 commented
I'm merging this now -- there are still a few things to do, including adding support for these caps to capDL, but kernel support is there.

2025-07-06 22:50 UTC, merged