aarch64,cortex-a53,hyp: Reduce seL4_UserTop value
seL4/seL4 pull request #265
Opened 2020-10-15 04:41 UTC by kent-mcleod

This ensures that no frames can be mapped that would overwrite the
currently stored VMID for the vspace.

Signed-off-by: Kent McLeod <kent@kry10.com>

2020-10-15 04:41 UTC, kent-mcleod commented
@ssrg-bamboo `test`

2020-10-15 04:43 UTC, ssrg-bamboo commented
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

2020-10-15 04:53 UTC, xurtis commented on libsel4/sel4_arch_include/aarch64/sel4/sel4_arch/constants.h
> +#define seL4_UserTop (0x000000ffffffffff- seL4_VSpaceReservedSlots * (UL_CONST(1) << (40 - seL4_VSpaceIndexBitsnot)))
What is `seL4_VSpaceIndexBitsnot`?

2020-10-15 04:56 UTC, kent-mcleod commented on libsel4/sel4_arch_include/aarch64/sel4/sel4_arch/constants.h
> +#define seL4_UserTop (0x000000ffffffffff- seL4_VSpaceReservedSlots * (UL_CONST(1) << (40 - seL4_VSpaceIndexBitsnot)))
A formatting error?

2020-10-15 05:18 UTC, ssrg-bamboo commented
## Test results for commit 35314621bf3802fbcdd42aeac839faebe21f44c9

### Summary

| Test name | Result |
| --- | --- |
| Code Quality - C Parser - EXT-seL4-kent-usertop-265 | SUCCESSFUL |
| Code Quality - Check licenses - seL4 - EXT-seL4-kent-usertop-265 | SUCCESSFUL |
| Code Quality - Reuse License Check - seL4 - EXT-seL4-kent-usertop-265 | SUCCESSFUL |
| Code Quality - Signed-off-by - seL4 - EXT-seL4-kent-usertop-265 | SUCCESSFUL |
| Code Quality - Style - seL4 - EXT-seL4-kent-usertop-265 | SUCCESSFUL |
| Dev seL4 tests - seL4 PRs: Kernel Compile - EXT-seL4-kent-usertop-265 | SUCCESSFUL |
| Dev seL4 tests - seL4 PRs: Preprocess - EXT-seL4-kent-usertop-265 | SUCCESSFUL |
| Dev seL4 tests - seL4 PRs: compile seL4test - EXT-seL4-kent-usertop-265 | FAILED |

### Detailed failure logs

| Project | Stage | Result summary |
| --- | --- | --- |
| Dev seL4 tests - seL4 PRs: compile seL4test - EXT-seL4-kent-usertop-265 | Build | 4 of 15 jobs failed |

**Job: gcc-armv8a-hw-build-1**
Build logs

    15-Oct-2020 15:49:28	Build Dev seL4 tests - seL4 PRs: compile seL4test - EXT-seL4-kent-usertop-265 - gcc-armv8a-hw-build-1 #1 (SEL4-PHT1545-GCCARMV8AHWBUILD1ID-1) started building on agent Elastic Agent on i-08a498b315631d882
    15-Oct-2020 15:49:28	Elastic agent on instance i-08a498b315631d882
    15-Oct-2020 15:49:28	Build working directory is /home/bamboo/bamboo-agent-home/xml-data/build-dir/SEL4-PHT1545-GCCARMV8AHWBUILD1ID
    15-Oct-2020 15:49:28	a670e336acca71e8354eae804a93cb11f6dae79b36ed72a63a8039db67716f9a
    15-Oct-2020 15:49:30	Executing build Dev seL4 tests - seL4 PRs: compile seL4test - EXT-seL4-kent-usertop-265 - gcc-armv8a-hw-build-1 #1 (SEL4-PHT1545-GCCARMV8AHWBUILD1ID-1)
    15-Oct-2020 15:49:30	Preparing artifact 'code' for use at /home/bamboo/bamboo-agent-home/xml-data/build-dir/SEL4-PHT1545-GCCARMV8AHWBUILD1ID/. (location: .)
    15-Oct-2020 15:49:30	Artifact 'code' prepared in 383.9 ms at /home/bamboo/bamboo-agent-home/xml-data/build-dir/SEL4-PHT1545-GCCARMV8AHWBUILD1ID/code.tar.gz
    15-Oct-2020 15:49:30	Running pre-build action: VCS Version Collector
    15-Oct-2020 15:49:30	Starting task 'Untar code' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    15-Oct-2020 15:49:31	+ tar xf code.tar.gz --recursive-unlink
    15-Oct-2020 15:49:32	Finished task 'Untar code' with result: Success
    15-Oct-2020 15:49:32	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    15-Oct-2020 15:49:33	+ chmod -R o+rwx /home/bamboo/bamboo-agent-home/xml-data/build-dir/SEL4-PHT1545-GCCARMV8AHWBUILD1ID
    15-Oct-2020 15:49:33	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    15-Oct-2020 15:49:33	Starting task 'Set up and build' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    15-Oct-2020 15:49:34	+ rm -rf build
    15-Oct-2020 15:49:34	+ mkdir build
    15-Oct-2020 15:49:34	+ cd build
    15-Oct-2020 15:49:34	+ ../init-build.sh -DPLATFORM=am335x-boneblack -DBAMBOO=TRUE -DAARCH32=TRUE
    15-Oct-2020 15:49:34	correct_platform_strings: Attempting to correct PLATFORM: am335x-boneblack
    15-Oct-2020 15:49:34	loading initial cache file /home/bamboo/bamboo-agent-home/xml-data/build-dir/SEL4-PHT1545-GCCARMV8AHWBUILD1ID/projects/sel4test/settings.cmake
    15-Oct-2020 15:49:34	            to new valid KernelPlatform: am335x
    15-Oct-2020 15:49:34	                      KernelARMPlatform: am335x-boneblack
    15-Oct-2020 15:49:34	correct_platform_strings: Based on toolchain, setting KernelSel4Arch: aarch32
    15-Oct-2020 15:49:34	-- Found seL4: /home/bamboo/bamboo-agent-home/xml-data/build-dir/SEL4-PHT1545-GCCARMV8AHWBUILD1ID/kernel  
    15-Oct-2020 15:49:34	-- Found GCC with prefix arm-linux-gnueabi-
    15-Oct-2020 15:49:34	-- Found GCC with prefix arm-linux-gnueabi-
    15-Oct-2020 15:49:34	-- The C compiler identification is GNU 8.3.0
    15-Oct-2020 15:49:34	-- The CXX compiler identification is GNU 8.3.0
    15-Oct-2020 15:49:34	-- The ASM compiler identification is GNU
    15-Oct-2020 15:49:34	-- Found assembler: /usr/bin/arm-linux-gnueabi-gcc
    15-Oct-2020 15:49:34	-- Check for working C compiler: /usr/bin/arm-linux-gnueabi-gcc
    15-Oct-2020 15:49:34	-- Check for working C compiler: /usr/bin/arm-linux-gnueabi-gcc -- works
    15-Oct-2020 15:49:34	-- Detecting C compiler ABI info
    15-Oct-2020 15:49:34	-- Detecting C compiler ABI info - done
    15-Oct-2020 15:49:34	-- Detecting C compile features
    15-Oct-2020 15:49:34	-- Detecting C compile features - done
    15-Oct-2020 15:49:34	-- Check for working CXX compiler: /usr/bin/arm-linux-gnueabi-g++
    15-Oct-2020 15:49:34	-- Check for working CXX compiler: /usr/bin/arm-linux-gnueabi-g++ -- works
    15-Oct-2020 15:49:34	-- Detecting CXX compiler ABI info
    15-Oct-2020 15:49:34	-- Detecting CXX compiler ABI info - done
    15-Oct-2020 15:49:34	-- Detecting CXX compile features
    15-Oct-2020 15:49:35	-- Detecting CXX compile features - done
    15-Oct-2020 15:49:35	-- Found elfloader-tool: /home/bamboo/bamboo-agent-home/xml-data/build-dir/SEL4-PHT1545-GCCARMV8AHWBUILD1ID/tools/seL4/elfloader-tool  
    15-Oct-2020 15:49:35	-- /home/bamboo/bamboo-agent-home/xml-data/build-dir/SEL4-PHT1545-GCCARMV8AHWBUILD1ID/build/kernel/gen_headers/plat/machine/devices_gen.h is out of date. Regenerating...
    15-Oct-2020 15:49:35	WARNING:root:Only mapping 4096/8192 bytes from node /ocp/serial@44e09000, region 0. Set kernel_size in YAML to silence.
    15-Oct-2020 15:49:35	WARNING:root:Only mapping 4096/16384 bytes from node /ocp/l4_wkup@44c00000/prcm@200000, region 0. Set kernel_size in YAML to silence.
    15-Oct-2020 15:49:35	interrupts for device /ocp/serial@44e09000
    15-Oct-2020 15:49:35	interrupts for device /ocp/interrupt-controller@48200000
    15-Oct-2020 15:49:35	interrupts for device /ocp/timer@48044000
    15-Oct-2020 15:49:35	interrupts for device /ocp/l4_wkup@44c00000/prcm@200000
    15-Oct-2020 15:49:35	interrupts for device /ocp/wdt@44e35000
    15-Oct-2020 15:49:35	-- CPIO test cpio_reproducible_flag PASSED
    15-Oct-2020 15:49:35	-- Found musllibc: /home/bamboo/bamboo-agent-home/xml-data/build-dir/SEL4-PHT1545-GCCARMV8AHWBUILD1ID/projects/musllibc  
    15-Oct-2020 15:49:35	-- Found util_libs: /home/bamboo/bamboo-agent-home/xml-data/build-dir/SEL4-PHT1545-GCCARMV8AHWBUILD1ID/projects/util_libs  
    15-Oct-2020 15:49:35	-- Found seL4_libs: /home/bamboo/bamboo-agent-home/xml-data/build-dir/SEL4-PHT1545-GCCARMV8AHWBUILD1ID/projects/seL4_libs  
    15-Oct-2020 15:49:35	-- Found sel4_projects_libs: /home/bamboo/bamboo-agent-home/xml-data/build-dir/SEL4-PHT1545-GCCARMV8AHWBUILD1ID/projects/sel4_projects_libs  
    15-Oct-2020 15:49:35	-- Found sel4runtime: /home/bamboo/bamboo-agent-home/xml-data/build-dir/SEL4-PHT1545-GCCARMV8AHWBUILD1ID/projects/sel4runtime  
    15-Oct-2020 15:49:35	-- Performing Test HARD_FLOAT
    15-Oct-2020 15:49:35	-- Performing Test HARD_FLOAT - Failed
    15-Oct-2020 15:49:35	-- Performing Test SOFTFP_FLOAT
    15-Oct-2020 15:49:35	-- Performing Test SOFTFP_FLOAT - Success
    15-Oct-2020 15:49:35	-- Performing Test compiler_arch_test
    15-Oct-2020 15:49:35	-- Performing Test compiler_arch_test - Success
    15-Oct-2020 15:49:35	-- Detecting cached version of: musllibc
    15-Oct-2020 15:49:35	-- Found Git: /usr/bin/git (found version "2.20.1") 
    15-Oct-2020 15:49:35	--   musllibc is dirty - will build from source
    15-Oct-2020 15:49:35	-- Found PythonInterp: /usr/bin/python (found version "2.7.16") 
    15-Oct-2020 15:49:35	-- Found NANOPB: /home/bamboo/bamboo-agent-home/xml-data/build-dir/SEL4-PHT1545-GCCARMV8AHWBUILD1ID/tools/nanopb  
    15-Oct-2020 15:49:35	-- Configuring done
    15-Oct-2020 15:49:35	-- Generating done
    15-Oct-2020 15:49:35	-- Build files have been written to: /home/bamboo/bamboo-agent-home/xml-data/build-dir/SEL4-PHT1545-GCCARMV8AHWBUILD1ID/build
    15-Oct-2020 15:49:35	+ ninja
    15-Oct- [...]

2020-10-15 06:25 UTC, kent-mcleod commented
@ssrg-bamboo `test`

2020-10-15 06:26 UTC, ssrg-bamboo commented
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

2020-10-15 07:20 UTC, ssrg-bamboo commented
## Test results for commit bddc9a57c6ed95d8bdfc6407e56d4c6a18fc144f

### Summary

#### NOTE: some test results have been updated!

| Test name | Result |
| --- | --- |
| Code Quality - C Parser - EXT-seL4-kent-usertop-265 | SUCCESSFUL |
| Code Quality - Check licenses - seL4 - EXT-seL4-kent-usertop-265 | SUCCESSFUL |
| Code Quality - Reuse License Check - seL4 - EXT-seL4-kent-usertop-265 | SUCCESSFUL |
| Code Quality - Signed-off-by - seL4 - EXT-seL4-kent-usertop-265 | SUCCESSFUL |
| Code Quality - Style - seL4 - EXT-seL4-kent-usertop-265 | SUCCESSFUL |
| Dev seL4 tests - seL4 PRs: Kernel Compile - EXT-seL4-kent-usertop-265 | SUCCESSFUL |
| Dev seL4 tests - seL4 PRs: Preprocess - EXT-seL4-kent-usertop-265 | SUCCESSFUL |
| Dev seL4 tests - seL4 PRs: compile seL4test - EXT-seL4-kent-usertop-265 | FAILED |

### Detailed failure logs

| Project | Stage | Result summary |
| --- | --- | --- |
| Dev seL4 tests - seL4 PRs: compile seL4test - EXT-seL4-kent-usertop-265 | Build | 4 of 15 jobs failed |

**Job: gcc-armv8a-hw-build-1**
Build logs

    15-Oct-2020 17:49:17	Build Dev seL4 tests - seL4 PRs: compile seL4test - EXT-seL4-kent-usertop-265 - gcc-armv8a-hw-build-1 #2 (SEL4-PHT1545-GCCARMV8AHWBUILD1ID-2) started building on agent Elastic Agent on i-02fd29a15fd5611d7
    15-Oct-2020 17:49:17	Elastic agent on instance i-02fd29a15fd5611d7
    15-Oct-2020 17:49:17	Build working directory is /home/bamboo/bamboo-agent-home/xml-data/build-dir/SEL4-PHT1545-GCCARMV8AHWBUILD1ID
    15-Oct-2020 17:49:17	Unable to find image 'trustworthysystems/sel4:latest' locally
    15-Oct-2020 17:49:20	latest: Pulling from trustworthysystems/sel4
    15-Oct-2020 17:49:20	afb6ec6fdc1c: Already exists
    15-Oct-2020 17:49:20	61926a6ba970: Pulling fs layer
    15-Oct-2020 17:49:20	b3114d5edf22: Pulling fs layer
    15-Oct-2020 17:49:20	b8392b1574b8: Pulling fs layer
    15-Oct-2020 17:49:20	c66eb62acf3b: Pulling fs layer
    15-Oct-2020 17:49:20	61926a6ba970: Verifying Checksum
    15-Oct-2020 17:49:20	61926a6ba970: Download complete
    15-Oct-2020 17:49:20	b8392b1574b8: Verifying Checksum
    15-Oct-2020 17:49:20	b8392b1574b8: Download complete
    15-Oct-2020 17:49:20	61926a6ba970: Pull complete
    15-Oct-2020 17:49:21	b3114d5edf22: Verifying Checksum
    15-Oct-2020 17:49:21	b3114d5edf22: Download complete
    15-Oct-2020 17:49:25	c66eb62acf3b: Verifying Checksum
    15-Oct-2020 17:49:25	c66eb62acf3b: Download complete
    15-Oct-2020 17:49:27	b3114d5edf22: Pull complete
    15-Oct-2020 17:49:27	b8392b1574b8: Pull complete
    15-Oct-2020 17:49:59	c66eb62acf3b: Pull complete
    15-Oct-2020 17:49:59	Digest: sha256:8b69a2ba59c923767b8d56f09f551207331e18951b03dce1a1ee8b18ccfead61
    15-Oct-2020 17:49:59	Status: Downloaded newer image for trustworthysystems/sel4:latest
    15-Oct-2020 17:50:08	c28e237aa17d0c84b5ba8af9c643486e9bb9e44e7cc46ee976897d92bc4c366b
    15-Oct-2020 17:50:09	Executing build Dev seL4 tests - seL4 PRs: compile seL4test - EXT-seL4-kent-usertop-265 - gcc-armv8a-hw-build-1 #2 (SEL4-PHT1545-GCCARMV8AHWBUILD1ID-2)
    15-Oct-2020 17:50:09	Preparing artifact 'code' for use at /home/bamboo/bamboo-agent-home/xml-data/build-dir/SEL4-PHT1545-GCCARMV8AHWBUILD1ID/. (location: .)
    15-Oct-2020 17:50:10	Artifact 'code' prepared in 345.7 ms at /home/bamboo/bamboo-agent-home/xml-data/build-dir/SEL4-PHT1545-GCCARMV8AHWBUILD1ID/code.tar.gz
    15-Oct-2020 17:50:10	Running pre-build action: VCS Version Collector
    15-Oct-2020 17:50:10	Starting task 'Untar code' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    15-Oct-2020 17:50:11	+ tar xf code.tar.gz --recursive-unlink
    15-Oct-2020 17:50:11	Finished task 'Untar code' with result: Success
    15-Oct-2020 17:50:11	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    15-Oct-2020 17:50:12	+ chmod -R o+rwx /home/bamboo/bamboo-agent-home/xml-data/build-dir/SEL4-PHT1545-GCCARMV8AHWBUILD1ID
    15-Oct-2020 17:50:12	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    15-Oct-2020 17:50:12	Starting task 'Set up and build' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    15-Oct-2020 17:50:13	+ rm -rf build
    15-Oct-2020 17:50:13	+ mkdir build
    15-Oct-2020 17:50:13	+ cd build
    15-Oct-2020 17:50:13	+ ../init-build.sh -DPLATFORM=am335x-boneblack -DBAMBOO=TRUE -DAARCH32=TRUE
    15-Oct-2020 17:50:13	correct_platform_strings: Attempting to correct PLATFORM: am335x-boneblack
    15-Oct-2020 17:50:13	loading initial cache file /home/bamboo/bamboo-agent-home/xml-data/build-dir/SEL4-PHT1545-GCCARMV8AHWBUILD1ID/projects/sel4test/settings.cmake
    15-Oct-2020 17:50:13	            to new valid KernelPlatform: am335x
    15-Oct-2020 17:50:13	                      KernelARMPlatform: am335x-boneblack
    15-Oct-2020 17:50:13	correct_platform_strings: Based on toolchain, setting KernelSel4Arch: aarch32
    15-Oct-2020 17:50:13	-- Found seL4: /home/bamboo/bamboo-agent-home/xml-data/build-dir/SEL4-PHT1545-GCCARMV8AHWBUILD1ID/kernel  
    15-Oct-2020 17:50:13	-- Found GCC with prefix arm-linux-gnueabi-
    15-Oct-2020 17:50:13	-- Found GCC with prefix arm-linux-gnueabi-
    15-Oct-2020 17:50:13	-- The C compiler identification is GNU 8.3.0
    15-Oct-2020 17:50:13	-- The CXX compiler identification is GNU 8.3.0
    15-Oct-2020 17:50:13	-- The ASM compiler identification is GNU
    15-Oct-2020 17:50:13	-- Found assembler: /usr/bin/arm-linux-gnueabi-gcc
    15-Oct-2020 17:50:13	-- Check for working C compiler: /usr/bin/arm-linux-gnueabi-gcc
    15-Oct-2020 17:50:13	-- Check for working C compiler: /usr/bin/arm-linux-gnueabi-gcc -- works
    15-Oct-2020 17:50:13	-- Detecting C compiler ABI info
    15-Oct-2020 17:50:13	-- Detecting C compiler ABI info - done
    15-Oct-2020 17:50:13	-- Detecting C compile features
    15-Oct-2020 17:50:14	-- Detecting C compile features - done
    15-Oct-2020 17:50:14	-- Check for working CXX compiler: /usr/bin/arm-linux-gnueabi-g++
    15-Oct-2020 17:50:14	-- Check for working CXX compiler: /usr/bin/arm-linux-gnueabi-g++ -- works
    15-Oct-2020 17:50:14	-- Detecting CXX compiler ABI info
    15-Oct-2020 17:50:14	-- Detecting CXX compiler ABI info - done
    15-Oct-2020 17:50:14	-- Detecting CXX compile features
    15-Oct-2020 17:50:14	-- Detecting CXX compile features - done
    15-Oct-2020 17:50:14	-- Found elfloader-tool: /home/bamboo/bamboo-agent-home/xml-data/build-dir/SEL4-PHT1545-GCCARMV8AHWBUILD1ID/tools/seL4/elfloader-tool  
    15-Oct-2020 17:50:14	-- /home/bamboo/bamboo-agent-home/xml-data/build-dir/SEL4-PHT1545-GCCARMV8AHWBUILD1ID/build/kernel/gen_headers/plat/machine/devices_gen.h is out of date. Regenerating...
    15-Oct-2020 17:50:14	WARNING:root:Only mapping 4096/8192 bytes from node /ocp/serial@44e09000, region 0. Set kernel_size in YAML to silence.
    15-Oct-2020 17:50:14	WARNING:root:Only mapping 4096/16384 bytes from node /ocp/l4_wkup@44c00000/prcm@200000, region 0. Set kernel_size in YAML to silence.
    15-Oct-2020 17:50:14	interrupts for device /ocp/serial@44e09000
    15-Oct-2020 17:50:14	interrupts for device /ocp/interrupt-controller@48200000
    15-Oct-2020 17:50:14	interrupts for device /ocp/timer@48044000
    15-Oct-2020 17:50:14	interrupts for device /ocp/l4_wkup@44c00000/prcm@200000
    15-Oct-2020 17:50:14	interrupts for device /ocp/wdt@44e35000
    15-Oct-2020 17:50:14	-- CPIO test cpio_reproducible_flag PASSED
    15-Oct-2020 17:50:14	-- Found musllibc: /home/bamboo/bamboo-agent-home/xml-data/build-dir/SEL4-PHT1545-GCCARMV8AHWBUILD1ID/projects/musllibc  
    15-Oct-2020 17:50:14	-- Found util_libs: /home/bamboo/bamboo-agent-home/xml-data/build-dir/SEL4-PHT1545-GCCARMV8AHWBUILD1ID/projects/util_libs  
    15-Oct-2020 17:50:14	-- Found seL4_libs: /home/bamboo/bamboo-agent-home/xml-data/build-dir/SEL4-PHT1545-GCCARMV8AHWBUILD1ID/projects/seL4_libs  
    15-Oct-2020 17:50:14	-- Found sel4_projects_libs: /home/bamboo/bamboo-agen [...]

2020-10-15 08:27 UTC, xurtis approved these changes
LGTM

2020-10-15 08:30 UTC, xurtis requested changes
`libsel4` has no `UL_CONST`

2020-10-15 08:40 UTC, kent-mcleod commented
Ah, I only tested compiling the kernel.

2020-10-16 03:39 UTC, kent-mcleod commented
@ssrg-bamboo `test`

2020-10-16 03:40 UTC, ssrg-bamboo commented
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

2020-10-16 04:22 UTC, ssrg-bamboo commented
All the tests we ran have passed! Nice job!

2020-10-16 05:42 UTC, xurtis approved these changes

2020-10-16 06:09 UTC, merged