Release 12.0.0
seL4/seL4 pull request #273
Opened 2020-10-27 01:49 UTC by walle-whale

2020-10-27 02:27 UTC, pingerino requested changes

2020-10-27 02:27 UTC, pingerino commented on CHANGES
> +* Use correct configuration for TLS base.
Changes listed in the release notes should only document things that are user visible - API changes or behaviour changes. Remove anything that is superfluous to this - e.g "tweak section alignment".

2020-11-02 21:47 UTC, kent-mcleod commented
Somehow the following items were previously added to the changes file in the last release, when the changes were actually made after the release and should be included in this release:
```
* New fault type when running in Arm hypervisor mode: seL4_Fault_VPPIEvent
* New fault type when running in Arm hypervisor mode: seL4_Fault_VPPIEvent
    - The kernel can keep track of IRQ state for each VCPU for a reduced set of PPI IRQs and deliver IRQ events as
    - The kernel can keep track of IRQ state for each VCPU for a reduced set of PPI IRQs and deliver IRQ events as
      VCPU faults for these interrupt numbers.
      VCPU faults for these interrupt numbers.
    - Additionally a new VCPU invocation is introduced: seL4_ARM_VCPU_AckVPPI.
    - Additionally a new VCPU invocation is introduced: seL4_ARM_VCPU_AckVPPI.
      This is used to acknowledge a virtual PPI that was delivered as a fault.
      This is used to acknowledge a virtual PPI that was delivered as a fault.
* Virtualise Arm VTimer and Vtimer interrupts to support sharing across VCPUs.
* Virtualise Arm VTimer and Vtimer interrupts to support sharing across VCPUs.
  - A VCPU will now save and restore VTimer registers for the generic timer and also deliver a VTimer IRQ via a
  - A VCPU will now save and restore VTimer registers for the generic timer and also deliver a VTimer IRQ via a
    seL4_Fault_VPPIEvent fault. This enables multiple VCPUs bound to the same physical core to share this device.
    seL4_Fault_VPPIEvent fault. This enables multiple VCPUs bound to the same physical core to share this device.
* Build config option for whether WFE/WFI traps on VCPUs when running in Arm hypervisor mode
```

2020-11-05 00:47 UTC, walle-whale commented
@ssrg-bamboo `test`

2020-11-05 00:48 UTC, ssrg-bamboo commented
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

2020-11-05 01:19 UTC, ssrg-bamboo commented
## Test results for commit 78bfe657bbd52919d4f8cefa84310ef4df0fb147

### Summary

| Test name | Result |
| --- | --- |
| Code Quality - C Parser - EXT-seL4-release-12.0.0-273 | SUCCESSFUL |
| Code Quality - Check licenses - seL4 - EXT-seL4-release-12.0.0-273 | SUCCESSFUL |
| Code Quality - Reuse License Check - seL4 - EXT-seL4-release-12.0.0-273 | SUCCESSFUL |
| Code Quality - Signed-off-by - seL4 - EXT-seL4-release-12.0.0-273 | SUCCESSFUL |
| Code Quality - Style - seL4 - EXT-seL4-release-12.0.0-273 | FAILED |
| Dev seL4 tests - seL4 PRs: Kernel Compile - EXT-seL4-release-12.0.0-273 | SUCCESSFUL |
| Dev seL4 tests - seL4 PRs: Preprocess - EXT-seL4-release-12.0.0-273 | FAILED |
| Dev seL4 tests - seL4 PRs: compile seL4test - EXT-seL4-release-12.0.0-273 | SUCCESSFUL |

### Detailed failure logs

| Project | Stage | Result summary |
| --- | --- | --- |
| Code Quality - Style - seL4 - EXT-seL4-release-12.0.0-273 | Style check on changed files | 1 of 3 jobs failed |

**Job: shell**
Build logs

    05-Nov-2020 11:48:52	Build Code Quality - Style - seL4 - EXT-seL4-release-12.0.0-273 - shell #1 (CQ-SEL4STYLE415-SEL4SHELLPR-1) started building on agent A local agent 1
    05-Nov-2020 11:48:52	I run on the Bamboo server!
    05-Nov-2020 11:48:53	Build working directory is /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4STYLE415-SEL4SHELLPR
    05-Nov-2020 11:48:53	Executing build Code Quality - Style - seL4 - EXT-seL4-release-12.0.0-273 - shell #1 (CQ-SEL4STYLE415-SEL4SHELLPR-1)
    05-Nov-2020 11:48:53	Preparing artifact 'code' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4STYLE415-SEL4SHELLPR/. (location: .)
    05-Nov-2020 11:48:53	Artifact 'code' prepared in 27.78 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4STYLE415-SEL4SHELLPR/./code.tar.gz
    05-Nov-2020 11:48:53	Running pre-build action: VCS Version Collector
    05-Nov-2020 11:48:53	Starting task 'Untar code' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    05-Nov-2020 11:48:53	+ tar xf code.tar.gz --recursive-unlink
    05-Nov-2020 11:48:53	Finished task 'Untar code' with result: Success
    05-Nov-2020 11:48:53	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    05-Nov-2020 11:48:53	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4STYLE415-SEL4SHELLPR
    05-Nov-2020 11:48:53	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    05-Nov-2020 11:48:53	Starting task 'Check validity of shell scripts' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    05-Nov-2020 11:48:53	+ cd seL4
    05-Nov-2020 11:48:53	++ git diff --name-only 78bfe657bbd52919d4f8cefa84310ef4df0fb147 1f82755ef6c04fd9a54e1dabb0f85dc54cc6d21e
    05-Nov-2020 11:48:53	+ echo 'Checking shell style and syntax on CHANGES
    05-Nov-2020 11:48:53	VERSION'
    05-Nov-2020 11:48:53	+ git diff --name-only 78bfe657bbd52919d4f8cefa84310ef4df0fb147 1f82755ef6c04fd9a54e1dabb0f85dc54cc6d21e
    05-Nov-2020 11:48:53	Checking shell style and syntax on CHANGES
    05-Nov-2020 11:48:53	VERSION
    05-Nov-2020 11:48:53	+ xargs -d '\n' /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4STYLE415-SEL4SHELLPR/seL4_tools/misc/is-valid-shell-script
    05-Nov-2020 11:48:53	xargs: /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4STYLE415-SEL4SHELLPR/seL4_tools/misc/is-valid-shell-script: No such file or directory
    05-Nov-2020 11:48:53	Failing task since return code of [/var/atlassian/application-data/bamboo/temp/CQ-SEL4STYLE415-SEL4SHELLPR-1-ScriptBuildTask-6539338457140243806.sh] was 127 while expected 0
    05-Nov-2020 11:48:53	Finished task 'Check validity of shell scripts' with result: Failed
    05-Nov-2020 11:48:53	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    05-Nov-2020 11:48:53	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4STYLE415-SEL4SHELLPR
    05-Nov-2020 11:48:53	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    05-Nov-2020 11:48:53	Running post build plugin 'NCover Results Collector'
    05-Nov-2020 11:48:53	Running post build plugin 'Artifact Copier'
    05-Nov-2020 11:48:53	Running post build plugin 'npm Cache Cleanup'
    05-Nov-2020 11:48:53	Running post build plugin 'Clover Results Collector'
    05-Nov-2020 11:48:53	Running post build plugin 'Docker Container Cleanup'
    05-Nov-2020 11:48:53	Successfully removed working directory at '/var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4STYLE415-SEL4SHELLPR'
    05-Nov-2020 11:48:53	Finalising the build...
    05-Nov-2020 11:48:53	Stopping timer.
    05-Nov-2020 11:48:53	Build CQ-SEL4STYLE415-SEL4SHELLPR-1 completed.
    05-Nov-2020 11:48:53	Running on server: post build plugin 'NCover Results Collector'
    05-Nov-2020 11:48:53	Running on server: post build plugin 'Build Hanging Detection Configuration'
    05-Nov-2020 11:48:53	Running on server: post build plugin 'Clover Delta Calculator'
    05-Nov-2020 11:48:53	Running on server: post build plugin 'Maven Dependencies Postprocessor'
    05-Nov-2020 11:48:53	All post build plugins have finished
    05-Nov-2020 11:48:53	Generating build results summary...
    05-Nov-2020 11:48:53	Saving build results to disk...
    05-Nov-2020 11:48:53	Store variable context...
    05-Nov-2020 11:48:53	Indexing build results...
    05-Nov-2020 11:48:53	Finished building CQ-SEL4STYLE415-SEL4SHELLPR-1.


| Project | Stage | Result summary |
| --- | --- | --- |
| Dev seL4 tests - seL4 PRs: Preprocess - EXT-seL4-release-12.0.0-273 | Preprocess | 5 of 5 jobs failed |

**Job: ARM**
Build logs

    05-Nov-2020 11:55:35	Build Dev seL4 tests - seL4 PRs: Preprocess - EXT-seL4-release-12.0.0-273 - ARM #1 (SEL4-PFP1222-ARMPREPROCESS-1) started building on agent Elastic Agent on i-076401e78e57bf64d
    05-Nov-2020 11:55:35	Elastic agent on instance i-076401e78e57bf64d
    05-Nov-2020 11:55:35	Build working directory is /home/bamboo/bamboo-agent-home/xml-data/build-dir/SEL4-PFP1222-ARMPREPROCESS
    05-Nov-2020 11:55:35	Unable to find image 'trustworthysystems/l4v:latest' locally
    05-Nov-2020 11:55:37	latest: Pulling from trustworthysystems/l4v
    05-Nov-2020 11:55:37	afb6ec6fdc1c: Already exists
    05-Nov-2020 11:55:37	04c148c66a61: Already exists
    05-Nov-2020 11:55:37	5cfb1f4fbcb7: Already exists
    05-Nov-2020 11:55:37	85cd58b3d427: Already exists
    05-Nov-2020 11:55:37	7442521f47d1: Already exists
    05-Nov-2020 11:55:37	cfdd578c8143: Pulling fs layer
    05-Nov-2020 11:55:37	1d39fea6c4ed: Pulling fs layer
    05-Nov-2020 11:55:37	5f15d7b1e0b2: Pulling fs layer
    05-Nov-2020 11:55:37	755d2f78f40e: Pulling fs layer
    05-Nov-2020 11:55:37	e9efb75662b0: Pulling fs layer
    05-Nov-2020 11:55:38	cfdd578c8143: Verifying Checksum
    05-Nov-2020 11:55:38	cfdd578c8143: Download complete
    05-Nov-2020 11:55:38	5f15d7b1e0b2: Verifying Checksum
    05-Nov-2020 11:55:38	5f15d7b1e0b2: Download complete
    05-Nov-2020 11:55:38	755d2f78f40e: Verifying Checksum
    05-Nov-2020 11:55:38	755d2f78f40e: Download complete
    05-Nov-2020 11:55:38	cfdd578c8143: Pull complete
    05-Nov-2020 11:55:42	1d39fea6c4ed: Verifying Checksum
    05-Nov-2020 11:55:42	1d39fea6c4ed: Download complete
    05-Nov-2020 11:55:51	e9efb75662b0: Verifying Checksum
    05-Nov-2020 11:55:51	e9efb75662b0: Download complete
    05-Nov-2020 11:56:05	1d39fea6c4ed: Pull complete
    05-Nov-2020 11:56:06	5f15d7b1e0b2: Pull complete
    05-Nov-2020 11:56:07	755d2f78f40e: Pull complete
    05-Nov-2020 11:57:08	e9efb75662b0: Pull complete
    05-Nov-2020 11:57:08	Digest: sha256:7ce134aa575fb43abd176c191223be50075541dcf3b06c32f3651ae4df80a5c6
    05-Nov-2020 11:57:08	Status: Dow [...]

2020-12-02 01:55 UTC, axel-h commented
release has been made, closing this draft

2020-12-02 01:55 UTC, closed without merging