riscv: Clear reservation state on fastpath exit
seL4/seL4 pull request #276
Opened 2020-11-01 23:30 UTC by kent-mcleod

This operation matches the same operation performed by the slowpath
exit. It's purpose is to invalidate any existing reservation state from
the previous tcb context executing on this hart.

The fastpath must match a particular execution of the slowpath and so
these operations must match.

Signed-off-by: Kent McLeod <kent@kry10.com>

2020-11-01 23:30 UTC, kent-mcleod commented
This PR is adds a fastpath variant of what was added in https://github.com/seL4/seL4/pull/237

2020-11-01 23:47 UTC, lsf37 approved these changes
Looks good from my side. Added @Xaphiosis in case he has an opinion on this, but I don't think there is much choice, we do need equivalence.

The preprocess failure can be ignored, it is due to out-of-date state of the manifest because bamboo is still failing on some unrelated hardware tests.

2020-11-02 00:02 UTC, Xaphiosis approved these changes

2020-11-02 00:58 UTC, xurtis approved these changes

2020-11-02 00:58 UTC, xurtis commented
@ssrg-bamboo `test`

2020-11-02 00:59 UTC, ssrg-bamboo commented
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

2020-11-02 01:34 UTC, ssrg-bamboo commented
## Test results for commit ed9dfda529eec2a2b461ab784ed28c464c728d96

### Summary

| Test name | Result |
| --- | --- |
| Code Quality - C Parser - EXT-seL4-kent-riscv-fp-clear-res-276 | SUCCESSFUL |
| Code Quality - Check licenses - seL4 - EXT-seL4-kent-riscv-fp-clear-res-276 | SUCCESSFUL |
| Code Quality - Reuse License Check - seL4 - EXT-seL4-kent-riscv-fp-clear-res-276 | SUCCESSFUL |
| Code Quality - Signed-off-by - seL4 - EXT-seL4-kent-riscv-fp-clear-res-276 | SUCCESSFUL |
| Code Quality - Style - seL4 - EXT-seL4-kent-riscv-fp-clear-res-276 | SUCCESSFUL |
| Dev seL4 tests - seL4 PRs: Kernel Compile - EXT-seL4-kent-riscv-fp-clear-res-276 | SUCCESSFUL |
| Dev seL4 tests - seL4 PRs: Preprocess - EXT-seL4-kent-riscv-fp-clear-res-276 | SUCCESSFUL |
| Dev seL4 tests - seL4 PRs: compile seL4test - EXT-seL4-kent-riscv-fp-clear-res-276 | FAILED |

### Detailed failure logs

| Project | Stage | Result summary |
| --- | --- | --- |
| Dev seL4 tests - seL4 PRs: compile seL4test - EXT-seL4-kent-riscv-fp-clear-res-276 | Build | 6 of 15 jobs failed |

**Job: gcc-armv8a-hw-build-3**
Build logs

    02-Nov-2020 12:06:22	Build Dev seL4 tests - seL4 PRs: compile seL4test - EXT-seL4-kent-riscv-fp-clear-res-276 - gcc-armv8a-hw-build-3 #1 (SEL4-PHT1551-GCCARMV8AHWBUILD3ID-1) started building on agent Elastic Agent on i-0adabd4f40ccaf1d7
    02-Nov-2020 12:06:22	Elastic agent on instance i-0adabd4f40ccaf1d7
    02-Nov-2020 12:06:22	Build working directory is /home/bamboo/bamboo-agent-home/xml-data/build-dir/SEL4-PHT1551-GCCARMV8AHWBUILD3ID
    02-Nov-2020 12:06:24	Unable to find image 'trustworthysystems/sel4:latest' locally
    02-Nov-2020 12:06:26	latest: Pulling from trustworthysystems/sel4
    02-Nov-2020 12:06:26	afb6ec6fdc1c: Pulling fs layer
    02-Nov-2020 12:06:26	04c148c66a61: Pulling fs layer
    02-Nov-2020 12:06:26	5cfb1f4fbcb7: Pulling fs layer
    02-Nov-2020 12:06:26	85cd58b3d427: Pulling fs layer
    02-Nov-2020 12:06:26	7442521f47d1: Pulling fs layer
    02-Nov-2020 12:06:27	85cd58b3d427: Verifying Checksum
    02-Nov-2020 12:06:27	85cd58b3d427: Download complete
    02-Nov-2020 12:06:27	04c148c66a61: Verifying Checksum
    02-Nov-2020 12:06:27	04c148c66a61: Download complete
    02-Nov-2020 12:06:27	afb6ec6fdc1c: Verifying Checksum
    02-Nov-2020 12:06:27	afb6ec6fdc1c: Download complete
    02-Nov-2020 12:06:28	5cfb1f4fbcb7: Verifying Checksum
    02-Nov-2020 12:06:28	5cfb1f4fbcb7: Download complete
    02-Nov-2020 12:06:29	afb6ec6fdc1c: Pull complete
    02-Nov-2020 12:06:29	04c148c66a61: Pull complete
    02-Nov-2020 12:06:34	7442521f47d1: Verifying Checksum
    02-Nov-2020 12:06:34	7442521f47d1: Download complete
    02-Nov-2020 12:06:36	5cfb1f4fbcb7: Pull complete
    02-Nov-2020 12:06:36	85cd58b3d427: Pull complete
    02-Nov-2020 12:07:25	7442521f47d1: Pull complete
    02-Nov-2020 12:07:25	Digest: sha256:c50425f98fcde0074ba7b8b8c7f1e31067ed86224615932f1a6e4edd8aaee496
    02-Nov-2020 12:07:26	Status: Downloaded newer image for trustworthysystems/sel4:latest
    02-Nov-2020 12:07:31	f208e63cc2cf6f8a343297ef455cbb479f1de0d91b2c10bd302160877cd435ce
    02-Nov-2020 12:07:33	Executing build Dev seL4 tests - seL4 PRs: compile seL4test - EXT-seL4-kent-riscv-fp-clear-res-276 - gcc-armv8a-hw-build-3 #1 (SEL4-PHT1551-GCCARMV8AHWBUILD3ID-1)
    02-Nov-2020 12:07:33	Preparing artifact 'code' for use at /home/bamboo/bamboo-agent-home/xml-data/build-dir/SEL4-PHT1551-GCCARMV8AHWBUILD3ID/. (location: .)
    02-Nov-2020 12:07:34	Artifact 'code' prepared in 617.8 ms at /home/bamboo/bamboo-agent-home/xml-data/build-dir/SEL4-PHT1551-GCCARMV8AHWBUILD3ID/code.tar.gz
    02-Nov-2020 12:07:34	Running pre-build action: VCS Version Collector
    02-Nov-2020 12:07:34	Starting task 'Untar code' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    02-Nov-2020 12:07:35	+ tar xf code.tar.gz --recursive-unlink
    02-Nov-2020 12:07:36	Finished task 'Untar code' with result: Success
    02-Nov-2020 12:07:36	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    02-Nov-2020 12:07:37	+ chmod -R o+rwx /home/bamboo/bamboo-agent-home/xml-data/build-dir/SEL4-PHT1551-GCCARMV8AHWBUILD3ID
    02-Nov-2020 12:07:37	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    02-Nov-2020 12:07:37	Starting task 'Set up and build' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    02-Nov-2020 12:07:38	+ rm -rf build
    02-Nov-2020 12:07:38	+ mkdir build
    02-Nov-2020 12:07:38	+ cd build
    02-Nov-2020 12:07:38	+ ../init-build.sh -DPLATFORM=am335x-boneblack -DBAMBOO=TRUE -DAARCH32=TRUE -DVERIFICATION=TRUE
    02-Nov-2020 12:07:38	correct_platform_strings: Attempting to correct PLATFORM: am335x-boneblack
    02-Nov-2020 12:07:38	loading initial cache file /home/bamboo/bamboo-agent-home/xml-data/build-dir/SEL4-PHT1551-GCCARMV8AHWBUILD3ID/projects/sel4test/settings.cmake
    02-Nov-2020 12:07:38	            to new valid KernelPlatform: am335x
    02-Nov-2020 12:07:38	                      KernelARMPlatform: am335x-boneblack
    02-Nov-2020 12:07:38	correct_platform_strings: Based on toolchain, setting KernelSel4Arch: aarch32
    02-Nov-2020 12:07:38	-- Found seL4: /home/bamboo/bamboo-agent-home/xml-data/build-dir/SEL4-PHT1551-GCCARMV8AHWBUILD3ID/kernel  
    02-Nov-2020 12:07:38	-- Found GCC with prefix arm-linux-gnueabi-
    02-Nov-2020 12:07:38	-- Found GCC with prefix arm-linux-gnueabi-
    02-Nov-2020 12:07:38	-- The C compiler identification is GNU 8.3.0
    02-Nov-2020 12:07:38	-- The CXX compiler identification is GNU 8.3.0
    02-Nov-2020 12:07:38	-- The ASM compiler identification is GNU
    02-Nov-2020 12:07:38	-- Found assembler: /usr/bin/arm-linux-gnueabi-gcc
    02-Nov-2020 12:07:38	-- Check for working C compiler: /usr/bin/arm-linux-gnueabi-gcc
    02-Nov-2020 12:07:38	-- Check for working C compiler: /usr/bin/arm-linux-gnueabi-gcc -- works
    02-Nov-2020 12:07:38	-- Detecting C compiler ABI info
    02-Nov-2020 12:07:38	-- Detecting C compiler ABI info - done
    02-Nov-2020 12:07:38	-- Detecting C compile features
    02-Nov-2020 12:07:38	-- Detecting C compile features - done
    02-Nov-2020 12:07:38	-- Check for working CXX compiler: /usr/bin/arm-linux-gnueabi-g++
    02-Nov-2020 12:07:38	-- Check for working CXX compiler: /usr/bin/arm-linux-gnueabi-g++ -- works
    02-Nov-2020 12:07:38	-- Detecting CXX compiler ABI info
    02-Nov-2020 12:07:39	-- Detecting CXX compiler ABI info - done
    02-Nov-2020 12:07:39	-- Detecting CXX compile features
    02-Nov-2020 12:07:39	-- Detecting CXX compile features - done
    02-Nov-2020 12:07:39	-- Found elfloader-tool: /home/bamboo/bamboo-agent-home/xml-data/build-dir/SEL4-PHT1551-GCCARMV8AHWBUILD3ID/tools/seL4/elfloader-tool  
    02-Nov-2020 12:07:39	-- /home/bamboo/bamboo-agent-home/xml-data/build-dir/SEL4-PHT1551-GCCARMV8AHWBUILD3ID/build/kernel/gen_headers/plat/machine/devices_gen.h is out of date. Regenerating...
    02-Nov-2020 12:07:39	WARNING:root:Only mapping 4096/8192 bytes from node /ocp/serial@44e09000, region 0. Set kernel_size in YAML to silence.
    02-Nov-2020 12:07:39	WARNING:root:Only mapping 4096/16384 bytes from node /ocp/l4_wkup@44c00000/prcm@200000, region 0. Set kernel_size in YAML to silence.
    02-Nov-2020 12:07:39	interrupts for device /ocp/serial@44e09000
    02-Nov-2020 12:07:39	interrupts for device /ocp/interrupt-controller@48200000
    02-Nov-2020 12:07:39	interrupts for device /ocp/timer@48044000
    02-Nov-2020 12:07:39	interrupts for device /ocp/l4_wkup@44c00000/prcm@200000
    02-Nov-2020 12:07:39	interrupts for device /ocp/wdt@44e35000
    02-Nov-2020 12:07:39	-- CPIO test cpio_reproducible_flag PASSED
    02-Nov-2020 12:07:39	-- Found musllibc: /home/bamboo/bamboo-agent-home/xml-data/build-dir/SEL4-PHT1551-GCCARMV8AHWBUILD3ID/projects/musllibc  
    02-Nov-2020 12:07:39	-- Found util_libs: /home/bamboo/bamboo-agent-home/xml-data/build-dir/SEL4-PHT1551-GCCARM [...]

2020-11-02 05:36 UTC, sorear commented
So we _must_ clear the reservation on preemptive context switches, but we _may_ clear it at any other time.  The slowpath exit was an existing blob of asm that seemed like a natural fit, but it could also be done in the scheduler.

2020-11-02 06:10 UTC, kent-mcleod commented
Oh right, Arch_switchToThread is the place.  And the Arch_switchToThread aarch32 implementation already has a clear-exclusive-monitor inline asm.  @Xaphiosis how easy would it be to copy this operation for riscv: https://github.com/seL4/seL4/blob/master/src/arch/arm/32/kernel/thread.c#L22? 

In the meantime are there any objects to merging this PR, provided the operation doesn't have a material impact on the IPC cycle measurements?

2020-11-02 06:36 UTC, sorear commented
I don't think that helps here since the arm fastpath has a clearExMonitor_fp (and I suspect that approach adds more than one instruction here).

2020-11-02 06:42 UTC, kent-mcleod commented
Oh right.  Well thinking about it more now, the fastpath will always have a context switch and because we need to reset any reservations on a context switch we need to clear it somewhere in the fastpath and so clearing it in fastpath_restore should be adequate.

2020-11-02 06:43 UTC, kent-mcleod commented
err, apart from the cases where threads of the same address space are using the fastpath to communicate...

2020-11-02 06:53 UTC, sorear commented
The reservation needs to be cleared on preemptive switches between threads sharing a VSpace, so if VSpace checks are showing up something has gone wrong.

Does the argument in the 031b400a commit message that the reservation state is a message register make any sense to you?  sc is serializing on BOOM (I have not attempted to run sel4bench or otherwise quantify the cycle cost) and I was hoping to avoid an unnecessary one.

2020-11-02 07:07 UTC, kent-mcleod commented
> Does the argument in the 031b400 commit message that the reservation state is a message register make any sense to you? sc is serializing on BOOM (I have not attempted to run sel4bench or otherwise quantify the cycle cost) and I was hoping to avoid an unnecessary one.

I think I follow the argument:  By not invalidating the reservation state, the state is shared between both threads at each end of a fastpath operation and so they can use it to pass information across. But this doesn't give them any additional privileges as they can perform the same actions using message registers.  This relies on the property that the fastpath won't be taken if the scheduler needs to pick a third thread to switch to instead of the two communicating threads.

However there is still the requirement that the fastpath needs to have equivalent behavior to the slowpath and if the slowpath unconditionally invalidates the reservation upon returning to user level then the fastpath must do this also.  So it seems that if we don't want to perform a reservation invalidation on the fastpath, then we need to change the slowpath to not unconditionally invalidate the reservation.

2020-11-02 07:10 UTC, lsf37 commented
> So it seems that if we don't want to perform a reservation invalidation on the fastpath, then we need to change the slowpath to not unconditionally invalidate the reservation.

That sounds like a viable option to me.

2020-11-03 01:18 UTC, xurtis commented
Given we only want to clear the reservation state on switches that *aren't* direct IPC switches via an endpoint, characterising this in a manner that only excludes that case might be difficult.

2021-03-16 08:11 UTC, oliver-wm commented
How shall we go about resolving this?

2021-09-07 22:02 UTC, lsf37 requested changes
It looks like there are still changes to be made here, so marking the PR as that.

2021-09-30 09:18 UTC, kent-mcleod commented
Closing this and made issue: https://github.com/seL4/seL4/issues/604 as I'm unlikely to get to rewriting this PR anytime soon.

2021-09-30 09:18 UTC, closed without merging