add disabled config options as comments in the generated header files
seL4/seL4 pull request #379
Opened 2021-06-03 23:53 UTC by axel-h

Adding the disabled options as comment in the generated header files turned out quite useful to me when debugging things. It also reveals some oddities that might be worth cleaning up. Since we are doing debug builds, this is also some kind of debug information, especially when it comes to buildings system and different configuration. It might be something to be turnd off in release builds, but it does not do any harm there either and might even turn out to be useful there.

2021-06-04 06:50 UTC, kent-mcleod approved these changes

2021-06-04 19:56 UTC, axel-h commented
Please merge this if it passes the CI tests.

2021-06-04 23:08 UTC, lsf37 commented
@ssrg-bamboo `test`

2021-06-04 23:09 UTC, ssrg-bamboo commented
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

2021-06-04 23:53 UTC, ssrg-bamboo commented
## Test results for commit 8dbad94be04125a09fb38fff9b11a4f4a7ec8925

### Summary

| Test name | Result |
| --- | --- |
| Code Quality - C Parser - EXT-axel-h-patch-axel-14-379 | FAILED |
| Code Quality - Check licenses - seL4 - EXT-axel-h-patch-axel-14-379 | SUCCESSFUL |
| Code Quality - Reuse License Check - seL4 - EXT-axel-h-patch-axel-14-379 | SUCCESSFUL |
| Code Quality - Signed-off-by - seL4 - EXT-axel-h-patch-axel-14-379 | SUCCESSFUL |
| Code Quality - Style - seL4 - EXT-axel-h-patch-axel-14-379 | FAILED |
| Dev seL4 tests - seL4 PRs: Kernel Compile - EXT-axel-h-patch-axel-14-379 | SUCCESSFUL |
| Dev seL4 tests - seL4 PRs: Preprocess - EXT-axel-h-patch-axel-14-379 | SUCCESSFUL |
| Dev seL4 tests - seL4 PRs: compile seL4test - EXT-axel-h-patch-axel-14-379 | FAILED |

### Detailed failure logs

| Project | Stage | Result summary |
| --- | --- | --- |
| Code Quality - C Parser - EXT-axel-h-patch-axel-14-379 | Set GitHub Success/Fail [Run C-Parser] | 1 of 1 job failed |

**Job: Set notifications [Run C-Parser]**
Build logs

    05-Jun-2021 09:26:32	Build Code Quality - C Parser - EXT-axel-h-patch-axel-14-379 - Set notifications [Run C-Parser] #1 (CQ-CPARSE462-RUNCPARSERGHSTATUS-1) started building on agent rpi3, bamboo version: 7.1.4
    05-Jun-2021 09:26:32	RaspberryPi3
    05-Jun-2021 09:26:32	Build working directory is /var/atlassian/application-data/bamboo/xml-data/build-dir/96010243/CQ-CPARSE462-RUNCPARSERGHSTATUS
    05-Jun-2021 09:26:32	Executing build Code Quality - C Parser - EXT-axel-h-patch-axel-14-379 - Set notifications [Run C-Parser] #1 (CQ-CPARSE462-RUNCPARSERGHSTATUS-1)
    05-Jun-2021 09:26:32	Preparing artifact 'name.properties' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/96010243/CQ-CPARSE462-RUNCPARSERGHSTATUS/. (location: .)
    05-Jun-2021 09:26:32	Artifact 'name.properties' prepared in 10.66 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/96010243/CQ-CPARSE462-RUNCPARSERGHSTATUS/./name.properties
    05-Jun-2021 09:26:32	Preparing artifact 'sha.properties' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/96010243/CQ-CPARSE462-RUNCPARSERGHSTATUS/. (location: .)
    05-Jun-2021 09:26:32	Artifact 'sha.properties' prepared in 9.593 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/96010243/CQ-CPARSE462-RUNCPARSERGHSTATUS/./sha.properties
    05-Jun-2021 09:26:32	Preparing artifact 'success_Run_C-Parser_AARCH32CPARSE' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/96010243/CQ-CPARSE462-RUNCPARSERGHSTATUS/. (location: .)
    05-Jun-2021 09:26:32	Failure in artifact preparation phase during processing of: Subscription for Non required shared artifact: [success_Run_C-Parser_AARCH32CPARSE], pattern: [*.Run_C-Parser.success] anchored at: [.], destination: [.]
    05-Jun-2021 09:26:32	1 error(s) found when performing pre-build actions. 
    05-Jun-2021 09:26:32	Running on server: post build plugin 'NCover Results Collector'
    05-Jun-2021 09:26:32	Running on server: post build plugin 'Build Hanging Detection Configuration'
    05-Jun-2021 09:26:32	Running on server: post build plugin 'Clover Delta Calculator'
    05-Jun-2021 09:26:32	Running on server: post build plugin 'Maven Dependencies Postprocessor'
    05-Jun-2021 09:26:32	All post build plugins have finished
    05-Jun-2021 09:26:32	Generating build results summary...
    05-Jun-2021 09:26:32	Saving build results to disk...
    05-Jun-2021 09:26:32	Store variable context...
    05-Jun-2021 09:26:32	Indexing build results...
    05-Jun-2021 09:26:32	Finished building CQ-CPARSE462-RUNCPARSERGHSTATUS-1.


| Project | Stage | Result summary |
| --- | --- | --- |
| Code Quality - Style - seL4 - EXT-axel-h-patch-axel-14-379 | Style check on changed files | 1 of 3 jobs failed |

**Job: style**
Build logs

    05-Jun-2021 09:09:19	Build Code Quality - Style - seL4 - EXT-axel-h-patch-axel-14-379 - style #1 (CQ-SEL4STYLE481-SEL4STYLEPR-1) started building on agent A local agent 1, bamboo version: 7.1.4
    05-Jun-2021 09:09:19	I run on the Bamboo server!
    05-Jun-2021 09:09:19	Build working directory is /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4STYLE481-SEL4STYLEPR
    05-Jun-2021 09:09:19	Executing build Code Quality - Style - seL4 - EXT-axel-h-patch-axel-14-379 - style #1 (CQ-SEL4STYLE481-SEL4STYLEPR-1)
    05-Jun-2021 09:09:19	Preparing artifact 'code' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4STYLE481-SEL4STYLEPR/. (location: .)
    05-Jun-2021 09:09:19	Artifact 'code' prepared in 29.75 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4STYLE481-SEL4STYLEPR/./code.tar.gz
    05-Jun-2021 09:09:19	Running pre-build action: VCS Version Collector
    05-Jun-2021 09:09:19	Starting task 'Untar code' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    05-Jun-2021 09:09:19	+ tar xf code.tar.gz --recursive-unlink
    05-Jun-2021 09:09:19	Finished task 'Untar code' with result: Success
    05-Jun-2021 09:09:19	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    05-Jun-2021 09:09:19	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4STYLE481-SEL4STYLEPR
    05-Jun-2021 09:09:19	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    05-Jun-2021 09:09:19	Starting task 'Check style of changed files' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    05-Jun-2021 09:09:19	+ cd seL4
    05-Jun-2021 09:09:19	++ git merge-base 8dbad94be04125a09fb38fff9b11a4f4a7ec8925 db7bb413146f2a302579ff796507c059e25d22b1
    05-Jun-2021 09:09:19	+ git diff --name-only 8dbad94be04125a09fb38fff9b11a4f4a7ec8925 db7bb413146f2a302579ff796507c059e25d22b1
    05-Jun-2021 09:09:19	+ xargs -d '\n' /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4STYLE481-SEL4STYLEPR/standard_seL4_tools/misc/style.sh
    05-Jun-2021 09:09:19	style-cmake.sh: fatal error: need version 0.4.5 of cmake-format; Traceback (most recent call last):
    05-Jun-2021 09:09:19	  File "/usr/local/bin/cmake-format", line 33, in <module>
    05-Jun-2021 09:09:19	    sys.exit(load_entry_point('cmake-format==0.4.5', 'console_scripts', 'cmake-format')())
    05-Jun-2021 09:09:19	  File "/usr/local/bin/cmake-format", line 22, in importlib_load_entry_point
    05-Jun-2021 09:09:19	    for entry_point in distribution(dist_name).entry_points
    05-Jun-2021 09:09:19	  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    05-Jun-2021 09:09:19	    return Distribution.from_name(distribution_name)
    05-Jun-2021 09:09:19	  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    05-Jun-2021 09:09:19	    raise PackageNotFoundError(name)
    05-Jun-2021 09:09:19	importlib.metadata.PackageNotFoundError: cmake-format is installed
    05-Jun-2021 09:09:19	CRITICAL:root:['tools/helpers.cmake'] failed with error code 2
    05-Jun-2021 09:09:19	b''
    05-Jun-2021 09:09:19	Failing task since return code of [/var/atlassian/application-data/bamboo/temp/CQ-SEL4STYLE481-SEL4STYLEPR-1-ScriptBuildTask-4881755525021596736.sh] was 123 while expected 0
    05-Jun-2021 09:09:19	Finished task 'Check style of changed files' with result: Failed
    05-Jun-2021 09:09:19	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    05-Jun-2021 09:09:19	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4STYLE481-SEL4STYLEPR
    05-Jun-2021 09:09:19	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    05-Jun-2021 09:09:19	Starting task 'Run astyle code insights' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    05-Jun-2021 09:09:19	+ cd seL4
    05-Jun-2021 09:09:19	++ cut -d/ -f4
    [...]

2021-06-08 23:59 UTC, kent-mcleod requested changes
These changes seem to change how the #defines are outputted.  See the compilation errors in: https://sel4.systems/~bamboo/logs/CQ-CPARSE462-CPARSERBUILDKERNELGHSTATUS/1/CQ-CPARSE462-AARCH64ID-1.log

2021-06-09 01:12 UTC, axel-h commented
Indeed.
```
build	04-Jun-2021 23:25:16	 #define CONFIG_ARM_SMMU 1
build	04-Jun-2021 23:25:16	kernel/gen_config/kernel/gen_config.h:31: note: this is the location of the previous definition
build	04-Jun-2021 23:25:16	 #define CONFIG_ARM_SMMU ON
```
But actually, I'd says that the `#define CONFIG_ARM_SMMU 1` is what we expect to see. While `#define CONFIG_ARM_SMMU ON` is broken. The CMake code is using:
```
if("${value}" STREQUAL "ON")            
    set(value 1)        
endif()
```
maybe that needs a mere general approach to catch everything that is "true". Or is there another place where the file are generated that also needs to be update then. Or is this a manifest issue that repos are not in sync? I'll have a look if I can find this, maybe it's something specific to 'PLATFORM=tx2', I did not test this platform.

2021-06-13 20:27 UTC, axel-h commented
* `CONFIG_ARM_SMMU` is set from multiple places, what is created has been synced now. The underlying issues, that multiple definition should not end up multiple times in the header files, has to be addressed separately. 
* reworked the ARM definitions now. Things are only set if ARM architecture is enabled, so we don't see this on RISC-V. Also based on the finding and asses a few status message to clarify what is used. I assume the big-litte concept is somehow supported and multiple Cortex-A types can be enabled, but `KernelArmCPU` just holds the one with the lowest type ID then?
* `armv7ve` seem the same hack like `ARM_HYP`, ideally all this would be just an additional flag only?

2021-06-13 20:27 UTC, axel-h commented
@ssrg-bamboo `test`

2021-06-20 02:51 UTC, kent-mcleod requested changes
Are you able to move the changes to seL4Config.cmake  out of this PR and into a separate one? I'd like the opportunity to discuss them without out blocking the disabled comments changes from being merged.

2021-06-20 02:59 UTC, kent-mcleod commented
> `CONFIG_ARM_SMMU` is set from multiple places, what is created has been synced now. The underlying issues, that multiple definition should not end up multiple times in the header files, has to be addressed separately.

You are right that the CONFIG_ARM_SMMU isn't being set correctly.  It is currently supposed to be an optional configuration that is only available on tx2.  This means that the `config_set(KernelArmSMMU ARM_SMMU "${KernelArmSMMU}")` line and `set(KernelArmSMMU ON)` in tx2/config.cmake should be removed, leaving just the `config_option(KernelArmSMMU ARM_SMMU "Enable SystemMMU" DEFAULT OFF DEPENDS "KernelPlatformTx2")` line in src/arm/config.cmake.

2021-06-20 03:57 UTC, kent-mcleod commented
> armv7ve seem the same hack like ARM_HYP, ideally all this would be just an additional flag only?

armv7ve is a different architecture from armv7-a from the compiler's point of view. Both options are recognized in -march= arguments. But armv7ve is also a superset of armv7-a so support for armv7ve implies support for armv7-a.  This same pattern would be found with the different armv8 versions(‘armv8-a’, ‘armv8.1-a’, ‘armv8.2-a’, ‘armv8.3-a’, ‘armv8.4-a’, ‘armv8.5-a’, ‘armv8.6-a’), but the kernel doesn't distinguish this yet.

2021-06-20 12:34 UTC, axel-h commented
removed the changes to `seL4Config.cmake`, this is now https://github.com/seL4/seL4/pull/402

2021-06-22 05:34 UTC, ssrg-bamboo commented
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

2021-06-25 08:03 UTC, ssrg-bamboo commented
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

2021-06-30 03:48 UTC, ssrg-bamboo commented
## Test results for commit f4dfb56ed494872f559a866ce6496de9f814f3aa

### Summary

#### NOTE: some test results have been updated!

| Test name | Result |
| --- | --- |
| Code Quality - C Parser - EXT-axel-h-patch-axel-14-379 | SUCCESSFUL |
| Code Quality - Check licenses - seL4 - EXT-axel-h-patch-axel-14-379 | FAILED |
| Code Quality - Reuse License Check - seL4 - EXT-axel-h-patch-axel-14-379 | SUCCESSFUL |
| Code Quality - Signed-off-by - seL4 - EXT-axel-h-patch-axel-14-379 | SUCCESSFUL |
| Code Quality - Style - seL4 - EXT-axel-h-patch-axel-14-379 | FAILED |
| Dev seL4 tests - seL4 PRs: Kernel Compile - EXT-axel-h-patch-axel-14-379 | SUCCESSFUL |
| Dev seL4 tests - seL4 PRs: Preprocess - EXT-axel-h-patch-axel-14-379 | SUCCESSFUL |
| Dev seL4 tests - seL4 PRs: compile seL4test - EXT-axel-h-patch-axel-14-379 | SUCCESSFUL |

### Detailed failure logs

| Project | Stage | Result summary |
| --- | --- | --- |
| Code Quality - Check licenses - seL4 - EXT-axel-h-patch-axel-14-379 | Check licenses | 1 of 1 job failed |

**Job: lic**
Build logs

    22-Jun-2021 15:34:35	Build Code Quality - Check licenses - seL4 - EXT-axel-h-patch-axel-14-379 - lic #2 (CQ-SEL4CL493-SEL4LICCQ-2) started building on agent A local agent 1, bamboo version: 7.1.4
    22-Jun-2021 15:34:35	I run on the Bamboo server!
    22-Jun-2021 15:34:35	Build working directory is /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4CL493-SEL4LICCQ
    22-Jun-2021 15:34:35	Executing build Code Quality - Check licenses - seL4 - EXT-axel-h-patch-axel-14-379 - lic #2 (CQ-SEL4CL493-SEL4LICCQ-2)
    22-Jun-2021 15:34:35	Preparing artifact 'code' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4CL493-SEL4LICCQ/. (location: .)
    22-Jun-2021 15:34:35	Artifact 'code' prepared in 11.86 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4CL493-SEL4LICCQ/./code.tar.gz
    22-Jun-2021 15:34:35	Running pre-build action: VCS Version Collector
    22-Jun-2021 15:34:35	Starting task 'Untar code' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    22-Jun-2021 15:34:35	+ tar xf code.tar.gz --recursive-unlink
    22-Jun-2021 15:34:35	Finished task 'Untar code' with result: Success
    22-Jun-2021 15:34:35	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    22-Jun-2021 15:34:35	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4CL493-SEL4LICCQ
    22-Jun-2021 15:34:35	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    22-Jun-2021 15:34:35	Starting task 'Check license' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    22-Jun-2021 15:34:35	+ python license-tool/check_license.py seL4 --spdx
    22-Jun-2021 15:34:36	ERROR:root:seL4/manual/logos/blacktriangle.pdf: seL4/manual/logos/blacktriangle.pdf: no owner found
    22-Jun-2021 15:34:36	ERROR:root:seL4/manual/logos/seL4-Foundation-logo.pdf: seL4/manual/logos/seL4-Foundation-logo.pdf: no owner found
    22-Jun-2021 15:34:36	Failing task since return code of [/var/atlassian/application-data/bamboo/temp/CQ-SEL4CL493-SEL4LICCQ-2-ScriptBuildTask-6145848822548404018.sh] was 1 while expected 0
    22-Jun-2021 15:34:36	Finished task 'Check license' with result: Failed
    22-Jun-2021 15:34:36	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    22-Jun-2021 15:34:36	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4CL493-SEL4LICCQ
    22-Jun-2021 15:34:36	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    22-Jun-2021 15:34:36	Running post build plugin 'NCover Results Collector'
    22-Jun-2021 15:34:36	Running post build plugin 'Artifact Copier'
    22-Jun-2021 15:34:36	Running post build plugin 'npm Cache Cleanup'
    22-Jun-2021 15:34:36	Running post build plugin 'Clover Results Collector'
    22-Jun-2021 15:34:36	Running post build plugin 'Docker Container Cleanup'
    22-Jun-2021 15:34:36	Successfully removed working directory at '/var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4CL493-SEL4LICCQ'
    22-Jun-2021 15:34:36	Finalising the build...
    22-Jun-2021 15:34:36	Stopping timer.
    22-Jun-2021 15:34:36	Build CQ-SEL4CL493-SEL4LICCQ-2 completed.
    22-Jun-2021 15:34:36	Running on server: post build plugin 'NCover Results Collector'
    22-Jun-2021 15:34:36	Running on server: post build plugin 'Build Hanging Detection Configuration'
    22-Jun-2021 15:34:36	Running on server: post build plugin 'Clover Delta Calculator'
    22-Jun-2021 15:34:36	Running on server: post build plugin 'Maven Dependencies Postprocessor'
    22-Jun-2021 15:34:36	All post build plugins have finished
    22-Jun-2021 15:34:36	Generating build results summary...
    22-Jun-2021 15:34:36	Saving build results to disk...
    22-Jun-2021 15:34:36	Store variable context...
    22-Jun-2021 15:34:36	Indexing build results...
    22-Jun-2021 15:34:36	Finished building CQ-SEL4CL493-SEL4LICCQ-2.


| Project | Stage | Result summary |
| --- | --- | --- |
| Code Quality - Style - seL4 - EXT-axel-h-patch-axel-14-379 | Style check on changed files | 1 of 3 jobs failed |

**Job: style**
Build logs

    22-Jun-2021 15:34:38	Build Code Quality - Style - seL4 - EXT-axel-h-patch-axel-14-379 - style #2 (CQ-SEL4STYLE481-SEL4STYLEPR-2) started building on agent A local agent 1, bamboo version: 7.1.4
    22-Jun-2021 15:34:38	I run on the Bamboo server!
    22-Jun-2021 15:34:38	Build working directory is /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4STYLE481-SEL4STYLEPR
    22-Jun-2021 15:34:38	Executing build Code Quality - Style - seL4 - EXT-axel-h-patch-axel-14-379 - style #2 (CQ-SEL4STYLE481-SEL4STYLEPR-2)
    22-Jun-2021 15:34:38	Preparing artifact 'code' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4STYLE481-SEL4STYLEPR/. (location: .)
    22-Jun-2021 15:34:38	Artifact 'code' prepared in 14.65 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4STYLE481-SEL4STYLEPR/./code.tar.gz
    22-Jun-2021 15:34:38	Running pre-build action: VCS Version Collector
    22-Jun-2021 15:34:38	Starting task 'Untar code' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    22-Jun-2021 15:34:38	+ tar xf code.tar.gz --recursive-unlink
    22-Jun-2021 15:34:38	Finished task 'Untar code' with result: Success
    22-Jun-2021 15:34:38	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    22-Jun-2021 15:34:38	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4STYLE481-SEL4STYLEPR
    22-Jun-2021 15:34:39	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    22-Jun-2021 15:34:39	Starting task 'Check style of changed files' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    22-Jun-2021 15:34:39	+ cd seL4
    22-Jun-2021 15:34:39	+ xargs -d '\n' /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4STYLE481-SEL4STYLEPR/standard_seL4_tools/misc/style.sh
    22-Jun-2021 15:34:39	++ git merge-base f4dfb56ed494872f559a866ce6496de9f814f3aa d1643774cdefd603f52a194fd6f87dca6872bb53
    22-Jun-2021 15:34:39	+ git diff --name-only f4dfb56ed494872f559a866ce6496de9f814f3aa 7a9cf4de10d20b27a932b4633099e536e9f2e7e2
    22-Jun-2021 15:34:39	style-cmake.sh: fatal error: need version 0.4.5 of cmake-format; Traceback (most recent call last):
    22-Jun-2021 15:34:39	  File "/usr/local/bin/cmake-format", line 33, in <module>
    22-Jun-2021 15:34:39	    sys.exit(load_entry_point('cmake-format==0.4.5', 'console_scripts', 'cmake-format')())
    22-Jun-2021 15:34:39	  File "/usr/local/bin/cmake-format", line 22, in impo [...]

2021-06-30 07:50 UTC, axel-h commented
Seem this bamboo failure is not related to my changes:
```
importlib.metadata.PackageNotFoundError: cmake-format is installed
22-Jun-2021 15:34:39	CRITICAL:root:['tools/helpers.cmake'] failed with error code 2
```

2021-07-01 02:05 UTC, merged