consolidate arm core specific constants
seL4/seL4 pull request #645
Opened 2021-11-16 01:24 UTC by axel-h

2021-11-16 08:00 UTC, axel-h commented on libsel4/sel4_plat_include/exynos5/sel4/plat/api/constants.h
> +#el#if defined(CONFIG_ARM_CORTEX_A15)
need to fix this
```suggestion
#elif defined(CONFIG_ARM_CORTEX_A15)
```

2021-11-16 21:17 UTC, axel-h commented
anybody has an idea why `TX2_debug_gcc_64 FAILED` failes?

2021-11-16 22:23 UTC, kent-mcleod requested changes
Thanks for this!  Are you able to use `_` instead of `-` in the new filenames to be consistent with other file in this interface.

2021-11-16 22:24 UTC, kent-mcleod commented
> anybody has an idea why `TX2_debug_gcc_64 FAILED` failes?

@lsf37 looks like the machine runner has lost permissions to the destination of the binary copy: 
`  Couldn't change mode of /tftpboot/tx2a/seL4-image: [Errno 1] Operation not permitted: '/tftpboot/tx2a/seL4-image'`

2021-11-16 22:33 UTC, lsf37 commented
> > anybody has an idea why `TX2_debug_gcc_64 FAILED` failes?
> 
> @lsf37 looks like the machine runner has lost permissions to the destination of the binary copy: ` Couldn't change mode of /tftpboot/tx2a/seL4-image: [Errno 1] Operation not permitted: '/tftpboot/tx2a/seL4-image'`

This bit is normal, and should really be fixed, it's happening for all runs (the user running this doesn't have enough permissions for changing permissions of the image, but doesn't really need to change them). The thing that went wrong in this one is

```
Retrieving file: /tx2a/pxelinux.cfg/default-arm
ethernet@2490000 Waiting for PHY auto negotiation to complete........ done
*** ERROR: `ipaddr' not set
 ```

which looks like a network fluke. I'll restart the test. @wom-bat this looks like a DHCP failure (but did work fine for all the other boards and also the other test runs of `tx2`).

2021-11-16 22:38 UTC, axel-h commented
> Are you able to use `_` instead of `-` in the new filenames to be consistent with other file in this interface.

Changed to underscores.

2021-11-16 22:41 UTC, lsf37 approved these changes

2021-11-23 04:10 UTC, axel-h commented
The changes affect ARM only, so I don't think the failing of HIFIVE_verification_gcc_64 is related.

2021-11-24 03:05 UTC, kent-mcleod approved these changes

2021-11-25 14:44 UTC, axel-h commented
HW Run `IMX8MM_EVK, armv8a, gcc` and `IMX8MM_EVK, armv8a, clang` fail now, see the board is stuck?

2021-11-28 04:07 UTC, lsf37 commented
Yes, someone was holding the lock for that board for a few days and blocked all the tests (you can see who in the logs ;-)). Seems like nobody but me is policing this, so it breaks when I'm on leave..

2021-11-29 22:10 UTC, merged