Make debug output for fault and dump a bit nicer
seL4/seL4 pull request #665
Opened 2021-11-25 15:45 UTC by axel-h

Improve the messages a bit to notalk about a "cap fault" just because there is no fault handler. Print a register snapshot besides the stack dump if  `CONFIG_DEBUG_BUILD` is enabled.

Fault printout for a null pointer dereferecne on RISC-V
```
## ==============================================================
## FAULT at PC=0x0 in thread 0xffffffc17fec7200 (rootserver)
## Cause: access fault on code at address 0x0, status 0x1
## Thread suspended, no userland fault handler (code 0)
## State snapshot:
##     x1/ra: 0x00000000'000150c6     x2/sp: 0x00000000'00143ea0
##     x3/gp: 0x00000000'00024800     x4/tp: 0x00000000'00144000
##     x5/t0: 0x00000000'00000000     x6/t1: 0x00000000'0001f5d8
##     x7/t2: 0x00000000'00000000     x8/s0: 0x00000000'00143ec0
##     x9/s1: 0x00000000'00000000    x10/a0: 0x00000000'00000000
##    x11/a1: 0x00000000'00000000    x12/a2: 0x00000000'00000000
##    x13/a3: 0x00000000'00000000    x14/a4: 0x00000000'00000000
##    x15/a5: 0x00000000'00000000    x16/a6: 0x00000000'00000000
##    x17/a7: 0xffffffff'fffffff7    x18/s2: 0x00000000'00000000
##    x19/s3: 0x00000000'00000000    x20/s4: 0x00000000'00000000
##    x21/s5: 0x00000000'00000000    x22/s6: 0x00000000'00000000
##    x23/s7: 0x00000000'00000000    x24/s8: 0x00000000'00000000
##    x25/s9: 0x00000000'00000000   x26/s10: 0x00000000'00000000
##   x27/s11: 0x00000000'00000000    x28/t3: 0x00000000'00000012
##    x29/t4: 0x00000000'20000000    x30/t5: 0x00000000'00000000
##    x31/t6: 0x00000000'00000000    scause: 0x00000000'0000000c
##   sstatus: 0x00000000'00000020   FaultIP: 0x00000000'00000000
##    NextIP: 0x00000000'00000000
##

Stack trace:
0x143ea0: 0x143ec0
0x143ea8: 0x101ea
0x143eb0: 0x143f00
0x143eb8: 0x14bcc
0x143ec0: 0x0
0x143ec8: 0x143f30
0x143ed0: 0x143f20
0x143ed8: 0x143f10
0x143ee0: 0x1
0x143ee8: 0x101d6
0x143ef0: 0x144000
0x143ef8: 0x14cf8
0x143f00: 0x0
0x143f08: 0x14a000
0x143f10: 0x20280
```

Scheduler dump ("RelQ" is only visible with MCS, "Core" only with SMP)
```
Dump of all TCBs (4):
  TCB              | State         | PC               | Prio | Core | RelQ | Name
  -----------------+---------------+------------------+------+------+------+----------------
  ffffffc100137600 | blocked/recv  | 1053a            |  255 |    0 |   no | main:fault_handler
  ffffffc100137200 | running       | 101f0            |  254 |    0 |   no | main:control
  ffffffff84028000 | idle          | 0                |    0 |    0 |   no | idle_thread
  ffffffc27ff0a200 | inactive      | 105dc            |  255 |    0 |   no | rootserver
```

2021-11-25 15:47 UTC, axel-h commented on src/kernel/faulthandler.c
>          current_lookup_fault = lookup_fault_missing_capability_new(0);
I wonder, do we really have to update `current_lookup_fault` here? Seems no body uses this.

2021-11-25 16:04 UTC, axel-h commented on src/kernel/debug.c
> +    for (tcb_t *tcb = specific_tcb ? specific_tcb : NODE_STATE(ksDebugTCBs);
I wonder if this should try to dump the scheduler on all cores on day and not just for the current core.

2021-11-28 03:57 UTC, lsf37 requested changes
It looks like there are lots of changes in here that break verification and are not needed to achieve the increased debug info. The effort for that would be in no relation to the improvement.

I'm also not convinced we do want that much info for every fault, e.g. there are lots of intended cap faults in sel4test and this looks like it would swamp the entire output. On the other hand I can see that this info could be very useful when no cap faults are intended.

What do others think of this?

2021-12-14 08:26 UTC, axel-h commented
I've reworked this now to have the changes only in the debug code that is invisible to the proofs. Let's see if this passes the proof test. Concerning the verbose output we could have another config flag here to reduce the debug output for seL4 test. Aside from this I'm open for ans specific help how we can tailor what it printed better to the cause.

2022-01-10 02:30 UTC, kent-mcleod commented
> I've reworked this now to have the changes only in the debug code that is invisible to the proofs. Let's see if this passes the proof test. Concerning the verbose output we could have another config flag here to reduce the debug output for seL4 test. Aside from this I'm open for ans specific help how we can tailor what it printed better to the cause.

Is there any existing issue about the kernel fault debug messages needing to be improved?  The kernel currently provides very simple debug fault console output and more detailed fault debug output can be implemented at user level. Shorter and simpler fault messages have an advantage of requiring the kernel spend less time generating and printing them and have less chance that the code to generate an error has an error itself.  It's also possible to modify the kernel code when debugging if additional information is needed without requiring this functionality to be merged upstream as it's not part of the verified configuration.

> Improve the messages a bit to no talk about a "cap fault" just because there is no fault handler. Print a register snapshot besides the stack dump if CONFIG_DEBUG_BUILD is enabled.

If there is no fault handler then it is correct to call it a cap fault because the kernel found no fault handler cap.

2022-01-10 02:47 UTC, axel-h commented
> It's also possible to modify the kernel code when debugging if additional information is needed without requiring this functionality to be merged upstream as it's not part of the verified configuration.

OK, making this PR a draft for now. Maybe this is also a candidate for having a configurable verbosity if debug kernel messages.

> If there is no fault handler then it is correct to call it a cap fault because the kernel found no fault handler cap.

Technically correct, my aim is just making the message be a bit more user friendly. I had to explain this message a couple of times now.

2022-05-30 13:18 UTC, closed without merging