avoid multiple definitions of vspace architecture specific function interface
seL4/seL4 pull request #795
Opened 2022-03-09 00:46 UTC by axel-h

The generic code uses these functions, thus there should be one common interface definition only.

I have not added these functions
- `bool_t CONST isValidVTableRoot(cap_t cap)`
- `void setVMRoot(tcb_t *tcb)`

because they exists for all architectures, but there is no generic code that uses them. Just the architecture specific code seem to follow a common pattern here.

2022-03-09 00:50 UTC, lsf37 commented
You're right that functions called from generic code should have their interface defined generically. Should not be proof-breaking, but I'm double-checking just in case.

2022-03-09 00:55 UTC, kent-mcleod requested changes
I don't think this needs changing.  Sometimes these functions end up getting implemented as static inline functions on some architectures and so trying to make them live in a shared header file when they don't have a single implementation isn't necessarily better.

2022-03-09 01:18 UTC, axel-h commented
> Sometimes these functions end up getting implemented as static inline functions

You are right, this would get difficult then. But in the case here I'd argue that it's not inlined , so we can be a bit more strict on the architecture interfaces definition to improve the code quality. We can worry about the inline thing if this happens.

2022-07-04 22:54 UTC, lsf37 commented
Let's close this one for now. I'm fine with the idea as such, but Kent is right, it's not high value-to-effort ratio and we'll probably see further conflicts with aarch64 work etc.

2022-07-04 22:54 UTC, closed without merging

2022-07-04 23:20 UTC, axel-h commented
Well, I can't really follow the argumentation actually and it lacks an example. The compiler might inline things at a certain optimization level anyway. The main intention of this PR is enforcing some interface between generic code and arch code that is easier to find (and harder to break by accident across architectures). I find it sad that there is not much interest in going that way.